# Optional external Meep scaffold for Robust candidate before/after
# Generated by L8.8 deterministic campaign fixtures.
# Browser FDTD execution is not implemented; adapt this file in an external Meep environment if needed.
SCENARIO_ID = "robust-candidate"
SCENE_HASH = "588269a545ca93a2"
REFERENCE_MODEL = "L8.7 before/after tolerance metrics"
