# Optional external Meep scaffold for Multi-element chain
# Generated by L8.8 deterministic campaign fixtures.
# Browser FDTD execution is not implemented; adapt this file in an external Meep environment if needed.
SCENARIO_ID = "multielement-chain"
SCENE_HASH = "588269a545ca93a2"
REFERENCE_MODEL = "stage-by-stage receipts"
