# Generated by EMMicro L8.1 External FDTD / Field Maps.
# Optional external helper only; the browser app does not execute FDTD.
# source_scenario_hash: 4bfd03c065f43f6e
# manifest_hash: eece0113ac228cd3

import json
import meep as mp

cell_size = mp.Vector3(12, 12, 25000)
resolution = 24
pml_layers = [mp.PML(0.75)]

materials = {
    "air": mp.Medium(index=1),  # k=0 hash=2653810c8f22d751
    "target-dielectric": mp.Medium(index=1),  # k=0 hash=364b4770be60882f
    "element-l83-aperture-blocker-blocker": mp.Medium(index=1.1),  # k=0.05 hash=4ff6536d42d40b9b
}

geometry = [
    mp.Block(center=mp.Vector3(0, 0, 22000), size=mp.Vector3(12, 12, 100), material=materials["target-dielectric"]),  # transparent-slab
    # finite-aperture-blocker: rectangular-aperture four-screen-block helper around aperture; diagnostic edge validation only
    mp.Block(center=mp.Vector3(-3.5, 0, 9500), size=mp.Vector3(3, 10, 0.8), material=materials["element-l83-aperture-blocker-blocker"]),
    mp.Block(center=mp.Vector3(3.5, 0, 9500), size=mp.Vector3(3, 10, 0.8), material=materials["element-l83-aperture-blocker-blocker"]),
    mp.Block(center=mp.Vector3(0, -4, 9500), size=mp.Vector3(4, 2, 0.8), material=materials["element-l83-aperture-blocker-blocker"]),
    mp.Block(center=mp.Vector3(0, 4, 9500), size=mp.Vector3(4, 2, 0.8), material=materials["element-l83-aperture-blocker-blocker"]),
]

sources = [
    mp.Source(mp.ContinuousSource(wavelength=0.5), component=mp.Ez, center=mp.Vector3(0, 0, 1000), size=mp.Vector3(12, 12, 0)),
]

sim = mp.Simulation(cell_size=cell_size, boundary_layers=pml_layers, geometry=geometry, sources=sources, resolution=resolution)

# Monitor definitions. External postprocess writes flux_summary.json and field_slice_xz.csv.
# monitor incident-flux: flux-plane center=(0, 0, 21500) size=(12, 12, 0) normal=+z
# monitor reflected-flux: flux-plane center=(0, 0, 21200) size=(12, 12, 0) normal=-z
# monitor transmitted-flux: flux-plane center=(0, 0, 22800) size=(12, 12, 0) normal=+z
# monitor field-slice-xz: field-slice center=(0, 0, 12500) size=(12, 0, 25000) normal=+y
# monitor l83-aperture-blocker-front-flux: flux-plane center=(0, 0, 9498.8) size=(10, 10, 0) normal=+z
# monitor l83-aperture-blocker-back-flux: flux-plane center=(0, 0, 9501.2) size=(10, 10, 0) normal=+z

# sim.run(until=200)
# sim.output_efield_z()
# Use tools/fdtd/postprocess_meep_output.py to produce importable JSON/CSV summaries.
