# Generated by EMMicro L8.1 External FDTD / Field Maps.
# Optional external helper only; the browser app does not execute FDTD.
# source_scenario_hash: a110586a3ad019e0
# manifest_hash: 9f35e9fe1bebdf17

import json
import meep as mp

cell_size = mp.Vector3(12, 12, 25000)
resolution = 24
pml_layers = [mp.PML(0.75)]

materials = {
    "air": mp.Medium(index=1),  # k=0 hash=2653810c8f22d751
    "target-dielectric": mp.Medium(index=1),  # k=0 hash=364b4770be60882f
    "element-l83-reflective-plate-ideal-reflector": mp.Medium(index=1000000),  # k=0 hash=d6b8aefb22bfb3a6
}

geometry = [
    mp.Block(center=mp.Vector3(0, 0, 22000), size=mp.Vector3(12, 12, 100), material=materials["target-dielectric"]),  # transparent-slab
    mp.Block(center=mp.Vector3(0, 0, 11000), size=mp.Vector3(8, 8, 0.5), material=mp.metal),  # finite-reflective-plate
]

sources = [
    mp.Source(mp.ContinuousSource(wavelength=0.5), component=mp.Ez, center=mp.Vector3(0, 0, 1000), size=mp.Vector3(12, 12, 0)),
]

sim = mp.Simulation(cell_size=cell_size, boundary_layers=pml_layers, geometry=geometry, sources=sources, resolution=resolution)

# Monitor definitions. External postprocess writes flux_summary.json and field_slice_xz.csv.
# monitor incident-flux: flux-plane center=(0, 0, 21500) size=(12, 12, 0) normal=+z
# monitor reflected-flux: flux-plane center=(0, 0, 21200) size=(12, 12, 0) normal=-z
# monitor transmitted-flux: flux-plane center=(0, 0, 22800) size=(12, 12, 0) normal=+z
# monitor field-slice-xz: field-slice center=(0, 0, 12500) size=(12, 0, 25000) normal=+y
# monitor l83-reflective-plate-front-flux: flux-plane center=(0, 0, 10999.25) size=(8, 8, 0) normal=+z
# monitor l83-reflective-plate-back-flux: flux-plane center=(0, 0, 11000.75) size=(8, 8, 0) normal=+z

# sim.run(until=200)
# sim.output_efield_z()
# Use tools/fdtd/postprocess_meep_output.py to produce importable JSON/CSV summaries.
