# L8.2 benchmark run: l82-transparent-slab-r10-pml0p5-pad1-m1p5
# padding_wavelengths: 1.00000
# monitor_offset_wavelengths: 1.50000
# run_until: 240.000
# Generated by EMMicro L8.1 External FDTD / Field Maps.
# Optional external helper only; the browser app does not execute FDTD.
# source_scenario_hash: 25afdd13c6357779
# manifest_hash: e9aebb4d58cad883

import json
import meep as mp

cell_size = mp.Vector3(12, 12, 25000)
resolution = 20
pml_layers = [mp.PML(0.5)]

materials = {
    "air": mp.Medium(index=1),  # k=0 hash=2653810c8f22d751
    "target-dielectric": mp.Medium(index=1),  # k=0 hash=364b4770be60882f
    "element-l83-tilted-wedge-dielectric": mp.Medium(index=1.5),  # k=0 hash=a003f6eddc217fef
}

geometry = [
    mp.Block(center=mp.Vector3(0, 0, 22000), size=mp.Vector3(12, 12, 100), material=materials["target-dielectric"]),  # transparent-slab
    mp.Block(center=mp.Vector3(0, 0, 10000), size=mp.Vector3(8, 8, 3), material=materials["element-l83-tilted-wedge-dielectric"], e1=mp.Vector3(0.978147600734, 0, 0.207911690818), e2=mp.Vector3(0, 1, 0), e3=mp.Vector3(-0.207911690818, 0, 0.978147600734)),  # tilted-interface-wedge
]

sources = [
    mp.Source(mp.ContinuousSource(wavelength=0.5), component=mp.Ez, center=mp.Vector3(0, 0, 1000), size=mp.Vector3(12, 12, 0)),
]

sim = mp.Simulation(cell_size=cell_size, boundary_layers=pml_layers, geometry=geometry, sources=sources, resolution=resolution)

# Monitor definitions. External postprocess writes flux_summary.json and field_slice_xz.csv.
# monitor incident-flux: flux-plane center=(0, 0, 21500) size=(12, 12, 0) normal=+z
# monitor reflected-flux: flux-plane center=(0, 0, 21200) size=(12, 12, 0) normal=-z
# monitor transmitted-flux: flux-plane center=(0, 0, 22800) size=(12, 12, 0) normal=+z
# monitor field-slice-xz: field-slice center=(0, 0, 12500) size=(12, 0, 25000) normal=+y
# monitor l83-tilted-wedge-front-flux: flux-plane center=(0, 0, 9995.5) size=(8, 8, 0) normal=+z
# monitor l83-tilted-wedge-back-flux: flux-plane center=(0, 0, 10004.5) size=(8, 8, 0) normal=+z

# sim.run(until=200)
# sim.output_efield_z()
# Use tools/fdtd/postprocess_meep_output.py to produce importable JSON/CSV summaries.
