# Generated by EMMicro L8.1 External FDTD / Field Maps.
# Optional external helper only; the browser app does not execute FDTD.
# source_scenario_hash: c4f75c6515cf0057
# manifest_hash: 4988876e01a19248

import json
import meep as mp

cell_size = mp.Vector3(16, 16, 60)
resolution = 16
pml_layers = [mp.PML(0.75)]

materials = {
    "air": mp.Medium(index=1),  # k=0 hash=2653810c8f22d751
    "target-dielectric": mp.Medium(index=1),  # k=0 hash=9a86ca1878c587aa
    "element-l84-circular-pinhole-blocker": mp.Medium(index=1.1),  # k=0.05 hash=69be4ab53b4d23f8
}

geometry = [
    mp.Block(center=mp.Vector3(0, 0, 58), size=mp.Vector3(16, 16, 100), material=materials["target-dielectric"]),  # transparent-slab
    # finite-aperture-blocker: circular-pinhole segmented screen helper; Meep run should use convergence/subpixel review before interpretation
    # aperture_radius_um=2 screen_radius_um=6
    mp.Block(center=mp.Vector3(3.69551813005, 1.53073372946, 25), size=mp.Vector3(4, 3.14159265359, 0.8), material=materials["element-l84-circular-pinhole-blocker"], e1=mp.Vector3(0.923879532511, 0.382683432365, 0), e2=mp.Vector3(-0.382683432365, 0.923879532511, 0), e3=mp.Vector3(0, 0, 1)),
    mp.Block(center=mp.Vector3(1.53073372946, 3.69551813005, 25), size=mp.Vector3(4, 3.14159265359, 0.8), material=materials["element-l84-circular-pinhole-blocker"], e1=mp.Vector3(0.382683432365, 0.923879532511, 0), e2=mp.Vector3(-0.923879532511, 0.382683432365, 0), e3=mp.Vector3(0, 0, 1)),
    mp.Block(center=mp.Vector3(-1.53073372946, 3.69551813005, 25), size=mp.Vector3(4, 3.14159265359, 0.8), material=materials["element-l84-circular-pinhole-blocker"], e1=mp.Vector3(-0.382683432365, 0.923879532511, 0), e2=mp.Vector3(-0.923879532511, -0.382683432365, 0), e3=mp.Vector3(0, 0, 1)),
    mp.Block(center=mp.Vector3(-3.69551813005, 1.53073372946, 25), size=mp.Vector3(4, 3.14159265359, 0.8), material=materials["element-l84-circular-pinhole-blocker"], e1=mp.Vector3(-0.923879532511, 0.382683432365, 0), e2=mp.Vector3(-0.382683432365, -0.923879532511, 0), e3=mp.Vector3(0, 0, 1)),
    mp.Block(center=mp.Vector3(-3.69551813005, -1.53073372946, 25), size=mp.Vector3(4, 3.14159265359, 0.8), material=materials["element-l84-circular-pinhole-blocker"], e1=mp.Vector3(-0.923879532511, -0.382683432365, 0), e2=mp.Vector3(0.382683432365, -0.923879532511, 0), e3=mp.Vector3(0, 0, 1)),
    mp.Block(center=mp.Vector3(-1.53073372946, -3.69551813005, 25), size=mp.Vector3(4, 3.14159265359, 0.8), material=materials["element-l84-circular-pinhole-blocker"], e1=mp.Vector3(-0.382683432365, -0.923879532511, 0), e2=mp.Vector3(0.923879532511, -0.382683432365, 0), e3=mp.Vector3(0, 0, 1)),
    mp.Block(center=mp.Vector3(1.53073372946, -3.69551813005, 25), size=mp.Vector3(4, 3.14159265359, 0.8), material=materials["element-l84-circular-pinhole-blocker"], e1=mp.Vector3(0.382683432365, -0.923879532511, 0), e2=mp.Vector3(0.923879532511, 0.382683432365, 0), e3=mp.Vector3(0, 0, 1)),
    mp.Block(center=mp.Vector3(3.69551813005, -1.53073372946, 25), size=mp.Vector3(4, 3.14159265359, 0.8), material=materials["element-l84-circular-pinhole-blocker"], e1=mp.Vector3(0.923879532511, -0.382683432365, 0), e2=mp.Vector3(0.382683432365, 0.923879532511, 0), e3=mp.Vector3(0, 0, 1)),
]

sources = [
    mp.Source(mp.ContinuousSource(wavelength=0.5), component=mp.Ez, center=mp.Vector3(0, 0, 4), size=mp.Vector3(16, 16, 0)),
]

sim = mp.Simulation(cell_size=cell_size, boundary_layers=pml_layers, geometry=geometry, sources=sources, resolution=resolution)

# Monitor definitions. External postprocess writes flux_summary.json and field_slice_xz.csv.
# monitor incident-flux: flux-plane center=(0, 0, 104) size=(16, 16, 0) normal=+z
# monitor reflected-flux: flux-plane center=(0, 0, 54) size=(16, 16, 0) normal=-z
# monitor transmitted-flux: flux-plane center=(0, 0, 55) size=(16, 16, 0) normal=+z
# monitor field-slice-xz: field-slice center=(0, 0, 30) size=(16, 0, 60) normal=+y
# monitor l84-circular-pinhole-front-flux: flux-plane center=(0, 0, 23.8) size=(12, 12, 0) normal=+z
# monitor l84-circular-pinhole-back-flux: flux-plane center=(0, 0, 26.2) size=(12, 12, 0) normal=+z

# sim.run(until=200)
# sim.output_efield_z()
# Use tools/fdtd/postprocess_meep_output.py to produce importable JSON/CSV summaries.
