# Generated by EMMicro L8.1 External FDTD / Field Maps.
# Optional external helper only; the browser app does not execute FDTD.
# source_scenario_hash: d96beb814449f702
# manifest_hash: 33d117e7c5e980b1

import json
import meep as mp

cell_size = mp.Vector3(16, 16, 60)
resolution = 16
pml_layers = [mp.PML(0.75)]

materials = {
    "air": mp.Medium(index=1),  # k=0 hash=2653810c8f22d751
    "target-dielectric": mp.Medium(index=1),  # k=0 hash=9a86ca1878c587aa
    "element-l84-long-slit-blocker": mp.Medium(index=1.1),  # k=0.05 hash=76b190e45283c189
}

geometry = [
    mp.Block(center=mp.Vector3(0, 0, 58), size=mp.Vector3(16, 16, 100), material=materials["target-dielectric"]),  # transparent-slab
    # finite-aperture-blocker: long-slit four-screen-block helper around aperture; diagnostic edge validation only
    mp.Block(center=mp.Vector3(-4, 0, 25), size=mp.Vector3(6, 14, 0.8), material=materials["element-l84-long-slit-blocker"]),
    mp.Block(center=mp.Vector3(4, 0, 25), size=mp.Vector3(6, 14, 0.8), material=materials["element-l84-long-slit-blocker"]),
]

sources = [
    mp.Source(mp.ContinuousSource(wavelength=0.5), component=mp.Ez, center=mp.Vector3(0, 0, 4), size=mp.Vector3(16, 16, 0)),
]

sim = mp.Simulation(cell_size=cell_size, boundary_layers=pml_layers, geometry=geometry, sources=sources, resolution=resolution)

# Monitor definitions. External postprocess writes flux_summary.json and field_slice_xz.csv.
# monitor incident-flux: flux-plane center=(0, 0, 104) size=(16, 16, 0) normal=+z
# monitor reflected-flux: flux-plane center=(0, 0, 54) size=(16, 16, 0) normal=-z
# monitor transmitted-flux: flux-plane center=(0, 0, 55) size=(16, 16, 0) normal=+z
# monitor field-slice-xz: field-slice center=(0, 0, 30) size=(16, 0, 60) normal=+y
# monitor l84-long-slit-front-flux: flux-plane center=(0, 0, 23.8) size=(14, 14, 0) normal=+z
# monitor l84-long-slit-back-flux: flux-plane center=(0, 0, 26.2) size=(14, 14, 0) normal=+z

# sim.run(until=200)
# sim.output_efield_z()
# Use tools/fdtd/postprocess_meep_output.py to produce importable JSON/CSV summaries.
