# Optional external Meep scaffold for Circular aperture
# Generated by L8.8 deterministic campaign fixtures.
# Browser FDTD execution is not implemented; adapt this file in an external Meep environment if needed.
SCENARIO_ID = "circular-pinhole"
SCENE_HASH = "4b5d69a020723f13"
REFERENCE_MODEL = "airy-bessel"
