# Optional external Meep scaffold for Long slit aperture
# Generated by L8.8 deterministic campaign fixtures.
# Browser FDTD execution is not implemented; adapt this file in an external Meep environment if needed.
SCENARIO_ID = "long-slit"
SCENE_HASH = "20016793069c92b3"
REFERENCE_MODEL = "single-slit-sinc2"
