# Optional external Meep scaffold for Absorbing slab
# Generated by L8.8 deterministic campaign fixtures.
# Browser FDTD execution is not implemented; adapt this file in an external Meep environment if needed.
SCENARIO_ID = "absorbing-slab"
SCENE_HASH = "982f243c1082d38f"
REFERENCE_MODEL = "beer-lambert"
