import { describe, expect, it } from "vitest";
import { solverDisclosureFor } from "./App";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { fileURLToPath } from "node:url";

const testDir = fileURLToPath(new URL(".", import.meta.url));

describe("solver disclosure copy", () => {
  it("labels the L2 result as a 1D scalar slice without claiming a full PSF", () => {
    const disclosure = solverDisclosureFor("scalar.angularSpectrum.l2.1d");

    expect(disclosure.label).toBe("L2 scalar 1D field propagation");
    expect(disclosure.detail).toBe("1D transverse slice; not a full circular-aperture Airy disk");
    expect(`${disclosure.label} ${disclosure.detail}`).not.toMatch(/Airy disk simulated|full PSF simulated|full microscope image simulated/i);
  });

  it("labels L2.5 sample propagation without claiming a microscope image", () => {
    const disclosure = solverDisclosureFor("scalar.angularSpectrum.l2.1d", true);

    expect(disclosure.label).toBe("L2 scalar 1D sample propagation");
    expect(disclosure.detail).toBe("1D coherent transverse slice; not a full microscope image, full PSF, or Airy disk");
    expect(`${disclosure.label} ${disclosure.detail}`).not.toMatch(/Airy disk simulated|full PSF simulated|full microscope image simulated/i);
  });

  it("labels L3 as a coherent scalar 2D approximation without claiming complete microscope physics", () => {
    const disclosure = solverDisclosureFor("scalar.coherent.l3.2d");

    expect(disclosure.label).toBe("L3 coherent 2D scalar image approximation");
    expect(disclosure.detail).toContain("2D coherent scalar image-plane intensity approximation");
    expect(`${disclosure.label} ${disclosure.detail}`).not.toMatch(/full microscope image|true microscope simulation|incoherent imaging|fluorescence simulated|vector PSF|Maxwell solver/i);
  });

  it("labels L3.3 as a partial-coherence scalar approximation without certified microscope claims", () => {
    const disclosure = solverDisclosureFor("scalar.partialCoherent.l3.3.2d");

    expect(disclosure.label).toBe("L3.3 partial-coherence scalar brightfield approximation");
    expect(disclosure.detail).toContain("source-angle intensity averaging");
    expect(`${disclosure.label} ${disclosure.detail}`).not.toMatch(/true 3D simulation|certified microscope simulation|vector optics simulated|fluorescence simulated|Maxwell solver/i);
  });

  it("keeps measured-data UI copy away from certified calibration claims", () => {
    const importPanel = readFileSync(resolve(testDir, "measurement/ImageImportPanel.tsx"), "utf8");
    const calibrationPanel = readFileSync(resolve(testDir, "measurement/CalibrationPanel.tsx"), "utf8");
    const roiPanel = readFileSync(resolve(testDir, "measurement/RoiPanel.tsx"), "utf8");

    expect(`${importPanel}\n${calibrationPanel}\n${roiPanel}`).not.toMatch(/certified ISO|certified EMVA|clinical calibration|hardware calibration/i);
  });

  it("labels L3.4B compare/fit as diagnostic measured-vs-simulated workbench output", () => {
    const comparePanel = readFileSync(resolve(testDir, "measurement/ComparePanel.tsx"), "utf8");
    const fitPanel = readFileSync(resolve(testDir, "measurement/FitPanel.tsx"), "utf8");

    expect(comparePanel).toContain("measured-vs-simulated workbench");
    expect(comparePanel).toContain("Not certified ISO 12233, EMVA 1288, clinical, or hardware calibration");
    expect(fitPanel).toContain("diagnostic only");
    expect(`${comparePanel}\n${fitPanel}`).not.toMatch(/certified ISO 12233 calibration|certified EMVA 1288 calibration|clinical calibration service|hardware calibration service/i);
  });

  it("labels L7.8 detector round-trip workflow over planar/scalar execution without claiming certified calibration, sensor-stack EM, arbitrary 3D EM, browser-native detector decoding, calibrated optical fitting, or lab metrology", () => {
    const maxwellPanel = readFileSync(resolve(testDir, "maxwell/MaxwellPanel.tsx"), "utf8");
    const explainability = readFileSync(resolve(testDir, "explainabilityContent.ts"), "utf8");
    const explainComponents = readFileSync(resolve(testDir, "explainability/Explainability.tsx"), "utf8");

    expect(maxwellPanel).toContain("L7.8 Detector Round-Trip Acceptance Pack / Real Detector Bridge");
    expect(maxwellPanel).toContain("diagnostic detector round-trip acceptance over board export, optional external detector helper output, JSON/CSV import, receipt/hash validation, ID matching, geometry fit, session QA, and evidence exports");
    expect(maxwellPanel).toContain("External Detector Bridge");
    expect(maxwellPanel).toContain("External Detector Round Trip");
    expect(maxwellPanel).toContain("Run Round-Trip Acceptance");
    expect(maxwellPanel).toContain("Export Round-Trip Evidence");
    expect(maxwellPanel).toContain("L7.8 detector round-trip wizard smoke preview");
    expect(maxwellPanel).toContain("L7.8 detector round-trip acceptance smoke preview");
    expect(maxwellPanel).toContain("L7.8 detector round-trip export smoke preview");
    expect(maxwellPanel).toContain("roundtrip_report.md");
    expect(maxwellPanel).toContain("roundtrip_report.json");
    expect(maxwellPanel).toContain("roundtrip_metrics.csv");
    expect(maxwellPanel).toContain("roundtrip_warnings.json");
    expect(maxwellPanel).toContain("OpenCV ChArUco detector JSON import");
    expect(maxwellPanel).toContain("Detector marker CSV import");
    expect(maxwellPanel).toContain("Export Board for Detector");
    expect(maxwellPanel).toContain("Load Example Detector JSON");
    expect(maxwellPanel).toContain("Load Example Detector CSV");
    expect(maxwellPanel).toContain("Import OpenCV ChArUco Detector Output");
    expect(maxwellPanel).toContain("Detector version");
    expect(maxwellPanel).toContain("Dictionary");
    expect(maxwellPanel).toContain("Parameters");
    expect(maxwellPanel).toContain("Import Detector CSV");
    expect(maxwellPanel).toContain("Validate Detection");
    expect(maxwellPanel).toContain("Compare Synthetic vs Imported");
    expect(maxwellPanel).toContain("Run Detector Geometry Fit");
    expect(maxwellPanel).toContain("Add Detector Frame to Session QA");
    expect(maxwellPanel).toContain("Export Detector Bridge Report");
    expect(maxwellPanel).toContain("Save Detector Bridge Study");
    expect(maxwellPanel).toContain("L7.7 detector bridge import smoke preview");
    expect(maxwellPanel).toContain("L7.7 detector receipt smoke preview");
    expect(maxwellPanel).toContain("L7.7 detector comparison smoke preview");
    expect(maxwellPanel).toContain("L7.7 detector fit handoff smoke preview");
    expect(maxwellPanel).toContain("L7.7 detector session handoff smoke preview");
    expect(maxwellPanel).toContain("detector_bridge_report.md");
    expect(maxwellPanel).toContain("detector_bridge_report.json");
    expect(maxwellPanel).toContain("imported_detections.csv");
    expect(maxwellPanel).toContain("detector_comparison.csv");
    expect(maxwellPanel).toContain("browser-native OpenCV.js/ArUco detector execution is not implemented");
    expect(maxwellPanel).toContain("Fiducial Board / ChArUco-style Target");
    expect(maxwellPanel).toContain("Diagnostic ChArUco-style synthetic fiducial board");
    expect(maxwellPanel).toContain("not OpenCV-compatible");
    expect(maxwellPanel).toContain("AprilTag decoding is not implemented");
    expect(maxwellPanel).toContain("Generate Fiducial Board");
    expect(maxwellPanel).toContain("Generate Synthetic Detections");
    expect(maxwellPanel).toContain("Load Example Fiducial JSON");
    expect(maxwellPanel).toContain("Import Fiducial JSON");
    expect(maxwellPanel).toContain("Match Fiducial IDs");
    expect(maxwellPanel).toContain("Reject Selected Marker");
    expect(maxwellPanel).toContain("Accept Selected Marker");
    expect(maxwellPanel).toContain("Move Selected Corner");
    expect(maxwellPanel).toContain("Relabel Selected Marker");
    expect(maxwellPanel).toContain("Run Fiducial Similarity Fit");
    expect(maxwellPanel).toContain("Run Fiducial Affine Fit");
    expect(maxwellPanel).toContain("Export Fiducial Bundle");
    expect(maxwellPanel).toContain("Add Fiducial Frame to Session QA");
    expect(maxwellPanel).toContain("Save Fiducial Study");
    expect(maxwellPanel).toContain("L7.5 fiducial board generator smoke preview");
    expect(maxwellPanel).toContain("L7.5 fiducial detection overlay smoke preview");
    expect(maxwellPanel).toContain("L7.5 partial-view coverage smoke preview");
    expect(maxwellPanel).toContain("L7.5 fiducial fit results smoke preview");
    expect(maxwellPanel).toContain("L7.5 fiducial session handoff smoke preview");
    expect(maxwellPanel).toContain("board_manifest.json");
    expect(maxwellPanel).toContain("fiducial_detection_report.md");
    expect(maxwellPanel).toContain("fiducial_detection_report.json");
    expect(maxwellPanel).toContain("matched_points.csv");
    expect(maxwellPanel).toContain("fitFiducialBoardDetection");
    expect(maxwellPanel).toContain("generateFiducialBoard");
    expect(maxwellPanel).toContain("generateSyntheticFiducialDetection");
    expect(maxwellPanel).toContain("parseFiducialDetectionJson");
    expect(maxwellPanel).toContain("applyFiducialManualEdits");
    expect(maxwellPanel).toContain("l74FrameFromFiducialFit");
    expect(maxwellPanel).toContain("l76CapabilitiesMatrix");
    expect(maxwellPanel).toContain("L7.8 detector round-trip acceptance reports are the executable scope");
    expect(maxwellPanel).toContain("browser-native OpenCV.js/ArUco detector execution, AprilTag decoding");
    expect(maxwellPanel).toContain("L7.4 Batch Measurement Session + Repeatability QA");
    expect(maxwellPanel).toContain("Batch Session Manifest");
    expect(maxwellPanel).toContain("Repeatability Thresholds");
    expect(maxwellPanel).toContain("Load Example Session Manifest");
    expect(maxwellPanel).toContain("Run Session QA");
    expect(maxwellPanel).toContain("Export Session QA");
    expect(maxwellPanel).toContain("Save Session Study");
    expect(maxwellPanel).toContain("Frame Review");
    expect(maxwellPanel).toContain("Aggregate Metrics");
    expect(maxwellPanel).toContain("Outlier Table");
    expect(maxwellPanel).toContain("Trend Plot");
    expect(maxwellPanel).toContain("session_report.md");
    expect(maxwellPanel).toContain("session_report.json");
    expect(maxwellPanel).toContain("frame_metrics.csv");
    expect(maxwellPanel).toContain("session_metrics.csv");
    expect(maxwellPanel).toContain("outliers.csv");
    expect(maxwellPanel).toContain("warnings.json");
    expect(maxwellPanel).toContain("parseL74SessionManifestCsv");
    expect(maxwellPanel).toContain("l74SyntheticFramesFromManifest");
    expect(maxwellPanel).toContain("runL74SessionQa");
    expect(maxwellPanel).toContain("sessionReportMarkdown");
    expect(maxwellPanel).toContain("frameMetricsCsv");
    expect(maxwellPanel).toContain("sessionMetricsCsv");
    expect(maxwellPanel).toContain("outliersCsv");
    expect(maxwellPanel).toContain("L7.4 diagnostic batch measurement session QA/repeatability aggregation");
    expect(maxwellPanel).toContain("certified metrology reports, lab-accredited metrology, lab accreditation workflows, hardware control");
    expect(maxwellPanel).toContain("L7.3 Measured Target Detection and ROI Hardening");
    expect(maxwellPanel).toContain("Import or generate measured target images, adjust ROI, auto-detect dot grids, correct points manually, fit L7.2 geometry, and export detection confidence reports.");
    expect(maxwellPanel).toContain("Measured Image Detection");
    expect(maxwellPanel).toContain("Detection Confidence Report");
    expect(maxwellPanel).toContain("Use Target As Measured Image");
    expect(maxwellPanel).toContain("Import Target Image");
    expect(maxwellPanel).toContain("Auto Detect");
    expect(maxwellPanel).toContain("Clear Detection");
    expect(maxwellPanel).toContain("Move Selected Point");
    expect(maxwellPanel).toContain("Reject Selected Point");
    expect(maxwellPanel).toContain("Run Geometry Fit");
    expect(maxwellPanel).toContain("Export Detection Report");
    expect(maxwellPanel).toContain("Save Detection Study");
    expect(maxwellPanel).toContain("ROI-limited dot-grid detection");
    expect(maxwellPanel).toContain("Checkerboard automatic detection is scaffold-only; AprilTag/ArUco fiducials are not implemented in L7.3.");
    expect(maxwellPanel).toContain("L7.2 generated geometric calibration target");
    expect(maxwellPanel).toContain("Geometric Calibration / Distortion Workbench");
    expect(maxwellPanel).toContain("Generate Dot/Grid Target");
    expect(maxwellPanel).toContain("Import Point CSV");
    expect(maxwellPanel).toContain("Import Point File");
    expect(maxwellPanel).toContain("Run Similarity Fit");
    expect(maxwellPanel).toContain("Run Affine Fit");
    expect(maxwellPanel).toContain("Run Radial Fit");
    expect(maxwellPanel).toContain("Compare Geometry");
    expect(maxwellPanel).toContain("Export Geometric Bundle");
    expect(maxwellPanel).toContain("Save Geometric Study");
    expect(maxwellPanel).toContain("Pixel scale");
    expect(maxwellPanel).toContain("Rotation");
    expect(maxwellPanel).toContain("Shear");
    expect(maxwellPanel).toContain("RMS residual");
    expect(maxwellPanel).toContain("Max residual");
    expect(maxwellPanel).toContain("Radial k1");
    expect(maxwellPanel).toContain("Residual vector map");
    expect(maxwellPanel).toContain("Corrected / undistorted points");
    expect(maxwellPanel).toContain("diagnostic 2D image geometry only; not certified camera calibration, lab metrology, full 3D pose/stereo calibration");
    expect(maxwellPanel).toContain("l76CapabilitiesMatrix");
    expect(maxwellPanel).toContain("generateGeometricCalibrationTarget");
    expect(maxwellPanel).toContain("fitGeometricCalibration");
    expect(maxwellPanel).toContain("parseGeometricPointCsv");
    expect(maxwellPanel).toContain("compareGeometricCalibrations");
    expect(maxwellPanel).toContain("geometricCalibrationReportMarkdown");
    expect(maxwellPanel).toContain("geometricResidualsCsv");
    expect(maxwellPanel).toContain("distortionMapCsv");
    expect(maxwellPanel).toContain("detectMeasuredTargetPoints");
    expect(maxwellPanel).toContain("pointSetFromDetection");
    expect(maxwellPanel).toContain("applyDetectionManualEdits");
    expect(maxwellPanel).toContain("detectionReportMarkdown");
    expect(maxwellPanel).toContain("detectedPointsCsv");
    expect(maxwellPanel).toContain("rejectedPointsCsv");
    expect(maxwellPanel).toContain("L7.1 Focus + Field MTF Qualification Workbench");
    expect(maxwellPanel).toContain("Run synthetic or current-frame focus MTF sweeps, map field ROIs, apply diagnostic thresholds");
    expect(maxwellPanel).toContain("Run Focus Sweep");
    expect(maxwellPanel).toContain("Import Current MTF Into Sweep");
    expect(maxwellPanel).toContain("Run Field Map");
    expect(maxwellPanel).toContain("Run Qualification");
    expect(maxwellPanel).toContain("Export Qualification Bundle");
    expect(maxwellPanel).toContain("Save Qualification Study");
    expect(maxwellPanel).toContain("Compare Focus Field MTF");
    expect(maxwellPanel).toContain("MTF50 vs focus");
    expect(maxwellPanel).toContain("Worst-field ROI");
    expect(maxwellPanel).toContain("L7.1 measured vs simulated focus/field MTF");
    expect(maxwellPanel).toContain("not ISO 12233 certification, Imatest-equivalent testing, calibrated optical model fitting");
    expect(maxwellPanel).toContain("L7.0 Slanted-Edge / Resolution Target MTF Workbench");
    expect(maxwellPanel).toContain("Import a batch manifest, normalize existing diagnostic frame metrics, aggregate repeatability and drift");
    expect(maxwellPanel).toContain("L7.2 diagnostic 2D geometric calibration/distortion/pixel-scale workflows, L7.3 diagnostic ROI-limited dot-grid measured target detection, L7.4 diagnostic batch measurement session QA/repeatability aggregation, L7.5 diagnostic synthetic fiducial board generation/imported detection matching/manual correction/session handoff, L7.7 external detector JSON/CSV import, detector receipt validation, comparison, report exports, and L7.8 detector round-trip acceptance reports are the executable scope");
    expect(maxwellPanel).toContain("Generate/import slanted-edge targets, compute ESF/LSF/SFR-MTF, compare measured vs simulated MTF, and sanity-check line-pair contrast.");
    expect(maxwellPanel).toContain("Generate Slanted Edge Target");
    expect(maxwellPanel).toContain("Run Slanted-Edge MTF");
    expect(maxwellPanel).toContain("Compare Blur Response");
    expect(maxwellPanel).toContain("Generate Line-Pair Target");
    expect(maxwellPanel).toContain("Export MTF Bundle");
    expect(maxwellPanel).toContain("Save MTF Study");
    expect(maxwellPanel).toContain("Send Camera DN Frame to MTF");
    expect(maxwellPanel).toContain("MTF50 / MTF10");
    expect(maxwellPanel).toContain("Measured vs Simulated MTF");
    expect(maxwellPanel).toContain("Line-Pair Target");
    expect(maxwellPanel).toContain("Camera Calibration Workbench");
    expect(maxwellPanel).toContain("This is an EMVA-inspired diagnostic calibration workflow.");
    expect(maxwellPanel).toContain("It is not an EMVA 1288 certification, ISO-certified calibration, lab-accredited camera characterization, sensor-stack EM, digital twin, or full 3D Maxwell/FDTD/FEM/BEM/RCWA execution.");
    expect(maxwellPanel).toContain("Calibration CSV summary");
    expect(maxwellPanel).toContain("Load Example Calibration CSV");
    expect(maxwellPanel).toContain("Load Example With photons_per_pixel");
    expect(maxwellPanel).toContain("Import Calibration CSV");
    expect(maxwellPanel).toContain("Run Photon-Transfer Fit");
    expect(maxwellPanel).toContain("Apply Calibrated Camera Profile");
    expect(maxwellPanel).toContain("Export Calibration Bundle");
    expect(maxwellPanel).toContain("Save Calibration Study");
    expect(maxwellPanel).toContain("Effective QE");
    expect(maxwellPanel).toContain("Residual RMS / max");
    expect(maxwellPanel).toContain("Linearity / SNR mismatch");
    expect(maxwellPanel).toContain("Camera / Sensor-Lite");
    expect(maxwellPanel).toContain("Convert selected simulated optical intensity into photons, electrons, DN, SNR, saturation, histogram, and line-profile evidence.");
    expect(maxwellPanel).toContain("Camera/Sensor-Lite converts an existing simulated intensity map into synthetic detector readout");
    expect(maxwellPanel).toContain("does not model pixel-level electromagnetic absorption, microlenses, color filters, charge diffusion, semiconductor transport, a calibrated sensor stack, certified EMVA compliance, digital twin behavior, or 3D Maxwell/FDTD/FEM/BEM/RCWA execution");
    expect(maxwellPanel).toContain("Pixel pitch um");
    expect(maxwellPanel).toContain("Sensor width px");
    expect(maxwellPanel).toContain("Sensor height px");
    expect(maxwellPanel).toContain("Quantum efficiency QE");
    expect(maxwellPanel).toContain("Exposure time ms");
    expect(maxwellPanel).toContain("Photon flux scale");
    expect(maxwellPanel).toContain("Full well e-");
    expect(maxwellPanel).toContain("Read noise e- RMS");
    expect(maxwellPanel).toContain("Dark current e-/px/s");
    expect(maxwellPanel).toContain("ADC bit depth");
    expect(maxwellPanel).toContain("Conversion gain DN/e-");
    expect(maxwellPanel).toContain("Black level DN");
    expect(maxwellPanel).toContain("Noise mode");
    expect(maxwellPanel).toContain("Generate Camera Output");
    expect(maxwellPanel).toContain("Saturate Exposure");
    expect(maxwellPanel).toContain("Export Camera Report");
    expect(maxwellPanel).toContain("Send synthetic camera image to Measured-vs-Simulated");
    expect(maxwellPanel).toContain("Save Camera Study");
    expect(maxwellPanel).toContain("Mean / peak photons");
    expect(maxwellPanel).toContain("Mean / peak electrons");
    expect(maxwellPanel).toContain("Mean / peak DN");
    expect(maxwellPanel).toContain("Saturation fraction");
    expect(maxwellPanel).toContain("Mean / peak SNR");
    expect(maxwellPanel).toContain("Dynamic range estimate");
    expect(maxwellPanel).toContain("Explain mode");
    expect(maxwellPanel).toContain("Show all explanations");
    expect(maxwellPanel).toContain("Under the hood: Airy/Bessel reference");
    expect(maxwellPanel).toContain("Under the hood: numerical propagation");
    expect(maxwellPanel).toContain("Under the hood: thin lens phase");
    expect(maxwellPanel).toContain("Under the hood: ExternalFdtdBackend");
    expect(explainComponents).toContain('role="tooltip"');
    expect(explainComponents).toContain("aria-describedby");
    expect(explainComponents).toContain("Escape");
    expect(explainComponents).toContain("ShowAllExplanationsDrawer");
    expect(explainComponents).not.toContain("title=");
    expect(explainability).toContain("validation.source.wavelength");
    expect(explainability).toContain("validation.analyticReference.airyBessel");
    expect(explainability).toContain("validation.numericalPropagation.huygensFresnel");
    expect(explainability).toContain("validation.residualMap");
    expect(explainability).toContain("validation.spatialBench");
    expect(explainability).toContain("validation.whereMeasured");
    expect(explainability).toContain("validation.radialOverlay");
    expect(explainability).toContain("validation.residualCurve");
    expect(explainability).toContain("validation.lens.thinLensPhase");
    expect(explainability).toContain("validation.lens.airyRadius");
    expect(explainability).toContain("validation.lens.focusMetric");
    expect(explainability).toContain("coherence.mode");
    expect(explainability).toContain("coherence.coherentFields");
    expect(explainability).toContain("coherence.incoherentIntensities");
    expect(explainability).toContain("coherence.gamma");
    expect(explainability).toContain("coherence.visibility");
    expect(explainability).toContain("coherence.formula");
    expect(explainability).toContain("coherence.orderSpacing");
    expect(explainability).toContain("coherence.slitGeometry");
    expect(explainability).toContain("backend.planarTmm");
    expect(explainability).toContain("backend.externalFdtdScaffold");
    expect(explainability).toContain("coating.planarStack");
    expect(explainability).toContain("coating.incidentMedium");
    expect(explainability).toContain("coating.substrateMedium");
    expect(explainability).toContain("coating.rtaMeasurementLocation");
    expect(explainability).toContain("coating.fieldMonitorLocation");
    expect(explainability).toContain("optimizer.coatingStack");
    expect(explainability).toContain("optimizer.candidateMaterials");
    expect(explainability).toContain("optimizer.applyCandidate");
    expect(explainability).toContain("coating.provenanceReceipt");
    expect(explainability).toContain("coating.reflectance");
    expect(explainability).toContain("robust.p90Score");
    expect(explainability).toContain("robust.sampleReduction");
    expect(explainability).toContain("No full 3D Maxwell, FDTD, FEM, BEM, RCWA");
    expect(maxwellPanel).toContain("L6.0 does not execute 3D Maxwell solves.");
    expect(maxwellPanel).toContain("It defines the 3D problem/result contract and external-backend export scaffold only.");
    expect(maxwellPanel).toContain("Validation Bench: spatial optical layout");
    expect(maxwellPanel).toContain("Coating Stack Workbench: planar layer model");
    expect(maxwellPanel).toContain("z = 0 mm Source");
    expect(maxwellPanel).toContain("Aperture / Slit / Lens");
    expect(maxwellPanel).toContain("Light direction");
    expect(maxwellPanel).toContain("Incident medium");
    expect(maxwellPanel).toContain("Where is this measured?");
    expect(maxwellPanel).toContain("Validation Bench");
    expect(maxwellPanel).toContain("Study Manager");
    expect(maxwellPanel).toContain("Save Study");
    expect(maxwellPanel).toContain("Load Study");
    expect(maxwellPanel).toContain("Duplicate Study");
    expect(maxwellPanel).toContain("Delete Study");
    expect(maxwellPanel).toContain("Export Study Bundle");
    expect(maxwellPanel).toContain("Import Study Bundle");
    expect(maxwellPanel).toContain("Copy Shareable URL");
    expect(maxwellPanel).toContain("Parameter Sweep Runner");
    expect(maxwellPanel).toContain("coherence gamma");
    expect(maxwellPanel).toContain("validation wavelength");
    expect(maxwellPanel).toContain("observation z");
    expect(maxwellPanel).toContain("slit width");
    expect(maxwellPanel).toContain("double-slit separation");
    expect(maxwellPanel).toContain("thin-lens defocus");
    expect(maxwellPanel).toContain("coating wavelength");
    expect(maxwellPanel).toContain("Run Sweep");
    expect(maxwellPanel).toContain("Cancel Sweep");
    expect(maxwellPanel).toContain("Sweep JSON");
    expect(maxwellPanel).toContain("Sweep Markdown");
    expect(maxwellPanel).toContain("Sweep CSV");
    expect(maxwellPanel).toContain("Measurement Tools");
    expect(maxwellPanel).toContain("Pin Crosshair");
    expect(maxwellPanel).toContain("Peak Finder");
    expect(maxwellPanel).toContain("Minimum Finder");
    expect(maxwellPanel).toContain("Profile CSV");
    expect(maxwellPanel).toContain("Measured-vs-Simulated");
    expect(maxwellPanel).toContain("Generate Synthetic CSV");
    expect(maxwellPanel).toContain("Import Measured CSV");
    expect(maxwellPanel).toContain("Import PNG/JPEG/CSV");
    expect(maxwellPanel).toContain("Compare Measured vs Simulated");
    expect(maxwellPanel).toContain("Run Diagnostic Fit");
    expect(maxwellPanel).toContain("Save Comparison Study");
    expect(maxwellPanel).toContain("Export Comparison Report");
    expect(maxwellPanel).toContain("diagnostic alignment and residual analysis, not certified instrument calibration");
    expect(maxwellPanel).toContain("Run Comparison");
    expect(maxwellPanel).toContain("Compare Gamma 1 vs Gamma 0");
    expect(maxwellPanel).toContain("Compare Selected Runs");
    expect(maxwellPanel).toContain("Comparison Markdown");
    expect(maxwellPanel).toContain("Comparison CSV");
    expect(maxwellPanel).toContain("Capabilities Matrix");
    expect(maxwellPanel).toContain("3D Maxwell solve");
    expect(maxwellPanel).toContain("not-implemented");
    expect(maxwellPanel).toContain("scaffold-only");
    expect(maxwellPanel).toContain("l76CapabilitiesMatrix");
    expect(maxwellPanel).toContain("runSyntheticFocusSweepMtf");
    expect(maxwellPanel).toContain("runFieldMtfMap");
    expect(maxwellPanel).toContain("qualifyFocusFieldMtf");
    expect(maxwellPanel).toContain("compareFocusFieldMtf");
    expect(maxwellPanel).toContain("runSlantedEdgeMtf");
    expect(maxwellPanel).toContain("generateSlantedEdgeTarget");
    expect(maxwellPanel).toContain("generateLinePairTarget");
    expect(maxwellPanel).toContain("compareMtfRuns");
    expect(maxwellPanel).toContain("runCameraCalibration");
    expect(maxwellPanel).toContain("parseCameraCalibrationCsv");
    expect(maxwellPanel).toContain("cameraCalibrationReportBundleJson");
    expect(maxwellPanel).toContain("runCameraSensorLite");
    expect(maxwellPanel).toContain("cameraReportBundleJson");
    expect(maxwellPanel).toContain("cameraRunToMeasuredDataset");
    expect(maxwellPanel).toContain("cameraMetricsCsv");
    expect(maxwellPanel).toContain("cameraProfileCsv");
    expect(maxwellPanel).toContain("cameraHistogramCsv");
    expect(maxwellPanel).toContain("compareMeasuredToSimulatedProfile");
    expect(maxwellPanel).toContain("parseMeasuredCsvProfile");
    expect(maxwellPanel).toContain("runL67DiagnosticFit");
    expect(maxwellPanel).toContain("measuredComparisonBundleJson");
    expect(maxwellPanel).toContain("createStudySnapshot");
    expect(maxwellPanel).toContain("studyBundleJson");
    expect(maxwellPanel).toContain("runCoherenceGammaSweep");
    expect(maxwellPanel).toContain("runCircularObservationZSweep");
    expect(maxwellPanel).toContain("runThinLensDefocusSweep");
    expect(maxwellPanel).toContain("compareStudyRuns");
    expect(maxwellPanel).toContain("createFieldMarker");
    expect(maxwellPanel).toContain("Physics exam sequence");
    expect(maxwellPanel).toContain("Circular pinhole Airy/Bessel");
    expect(maxwellPanel).toContain("Long single slit sinc^2");
    expect(maxwellPanel).toContain("Double slit / grating orders");
    expect(maxwellPanel).toContain("Ideal thin lens focal plane");
    expect(maxwellPanel).toContain("Coherence Demonstrator");
    expect(maxwellPanel).toContain("Coherence Demonstrator: double slit");
    expect(maxwellPanel).toContain("Degree of coherence |gamma12|");
    expect(maxwellPanel).toContain("Coherent fields");
    expect(maxwellPanel).toContain("Incoherent intensities");
    expect(maxwellPanel).toContain("Partial coherence");
    expect(maxwellPanel).toContain("Fringe visibility V");
    expect(maxwellPanel).toContain("V = (Imax - Imin) / (Imax + Imin)");
    expect(maxwellPanel).toContain("I = |U1|^2 + |U2|^2 + 2 Re(gamma12 U1 U2*)");
    expect(maxwellPanel).toContain("Gamma 1.00");
    expect(maxwellPanel).toContain("Gamma 0.50");
    expect(maxwellPanel).toContain("Gamma 0.00");
    expect(maxwellPanel).toContain("Coherent Map");
    expect(maxwellPanel).toContain("Incoherent Map");
    expect(maxwellPanel).toContain("Partial-Coherence Map");
    expect(maxwellPanel).toContain("Interference-Term Map");
    expect(maxwellPanel).toContain("Run Coherence Demo");
    expect(maxwellPanel).toContain("Coherence JSON");
    expect(maxwellPanel).toContain("Coherence Markdown");
    expect(maxwellPanel).toContain("Coherence CSV");
    expect(maxwellPanel).toContain("Coherence Demonstrator: double slit");
    expect(maxwellPanel).toContain("Advisor Review Mode");
    expect(maxwellPanel).toContain("Run Advisor Review");
    expect(maxwellPanel).toContain("Advisor Markdown");
    expect(maxwellPanel).toContain("Advisor JSON");
    expect(maxwellPanel).toContain("Advisor CSV");
    expect(maxwellPanel).toContain("y1 ~= 5.00 mm");
    expect(maxwellPanel).toContain("orders every 5.00 mm");
    expect(maxwellPanel).toContain("Slit JSON");
    expect(maxwellPanel).toContain("Slit Markdown");
    expect(maxwellPanel).toContain("Ideal thin lens focal-plane validation");
    expect(maxwellPanel).toContain("r1 ~= 1.22 lambda f / D = 61 um");
    expect(maxwellPanel).toContain("Lens phase");
    expect(maxwellPanel).toContain("Pupil D");
    expect(maxwellPanel).toContain("Numerical Focal Map");
    expect(maxwellPanel).toContain("Analytic Airy Map");
    expect(maxwellPanel).toContain("Focus Scan");
    expect(maxwellPanel).toContain("Run Lens Benchmark");
    expect(maxwellPanel).toContain("Lens JSON");
    expect(maxwellPanel).toContain("Lens Markdown");
    expect(maxwellPanel).toContain("Lens CSV");
    expect(maxwellPanel).toContain("runThinLensFocalValidation");
    expect(maxwellPanel).toContain("thinLensFocalValidationJson");
    expect(maxwellPanel).toContain("thinLensFocalValidationCsv");
    expect(maxwellPanel).toContain("runCoherenceDemonstrator");
    expect(maxwellPanel).toContain("coherenceDemonstratorJson");
    expect(maxwellPanel).toContain("coherenceDemonstratorCsv");
    expect(maxwellPanel).toContain("runSlitOrderValidation");
    expect(maxwellPanel).toContain("runAdvisorValidationReview");
    expect(maxwellPanel).toContain("slitOrderValidationJson");
    expect(maxwellPanel).toContain("advisorValidationReviewMarkdown");
    expect(maxwellPanel).toContain("Circular pinhole Airy/Bessel");
    expect(maxwellPanel).toContain("Circular aperture, not long slit");
    expect(maxwellPanel).toContain("hand-checkable scalar diffraction benchmarks with numerical results, analytic references, residuals, and report exports");
    expect(maxwellPanel).toContain("Computation mode");
    expect(maxwellPanel).toContain("Analytic Airy reference");
    expect(maxwellPanel).toContain("Numerical scalar propagation");
    expect(maxwellPanel).toContain("Compare numerical vs analytic");
    expect(maxwellPanel).toContain("Map grid");
    expect(maxwellPanel).toContain("Aperture radial");
    expect(maxwellPanel).toContain("Aperture angular");
    expect(maxwellPanel).toContain("Numerical Intensity Map");
    expect(maxwellPanel).toContain("Analytic Reference Map");
    expect(maxwellPanel).toContain("Residual Map");
    expect(maxwellPanel).toContain("Residual Curve");
    expect(maxwellPanel).toContain("Measured first min");
    expect(maxwellPanel).toContain("Finite-plane energy check");
    expect(maxwellPanel).toContain("Expected first Airy minimum");
    expect(maxwellPanel).toContain("Warning: first minimum is outside the 10 mm x 10 mm observation plane.");
    expect(maxwellPanel).toContain("Observation z");
    expect(maxwellPanel).toContain("Run Comparison");
    expect(maxwellPanel).toContain("Validation JSON");
    expect(maxwellPanel).toContain("Validation Markdown");
    expect(maxwellPanel).toContain("runCircularApertureValidation");
    expect(maxwellPanel).toContain("circularApertureValidationPipeline");
    expect(maxwellPanel).toContain("circularApertureValidationJson");
    expect(maxwellPanel).toContain("circularApertureValidationMarkdown");
    expect(maxwellPanel).toContain("Active solver backend");
    expect(maxwellPanel).toContain("PlanarTmmBackend");
    expect(maxwellPanel).toContain("ExternalFdtdBackend");
    expect(maxwellPanel).toContain("Future 3D Backends");
    expect(maxwellPanel).toContain("Scaffolded, not executable");
    expect(maxwellPanel).toContain("schema/export only in L6.0");
    expect(maxwellPanel).toContain("Export 3D FDTD Scaffold");
    expect(maxwellPanel).toContain("createMinimalMaxwellScene3D");
    expect(maxwellPanel).toContain("exportExternalFdtdScaffold");
    expect(maxwellPanel).toContain("externalFdtdSolverReceipt");
    expect(maxwellPanel).toContain("FEM/FDTD/BEM/RCWA");
    expect(maxwellPanel).toContain("solverBackend: run.solverBackend");
    expect(maxwellPanel).toContain("createMaterialCatalog");
    expect(maxwellPanel).toContain("listCatalogMaterials");
    expect(maxwellPanel).toContain("runCoatingSearch");
    expect(maxwellPanel).toContain("runRobustCoatingSearch");
    expect(maxwellPanel).toContain("runCoatingStack");
    expect(maxwellPanel).toContain("runCoatingSweep");
    expect(maxwellPanel).toContain("runCoatingDesignFoundry");
    expect(maxwellPanel).toContain("runCoatingYieldAnalysis");
    expect(maxwellPanel).toContain("serializeCoatingStackDesign");
    expect(maxwellPanel).toContain("parseMaterialImportJson");
    expect(maxwellPanel).toContain("Material Library");
    expect(maxwellPanel).toContain("MaterialPassport");
    expect(maxwellPanel).toContain("Template JSON");
    expect(maxwellPanel).toContain("Example Pack");
    expect(maxwellPanel).toContain("Example setup");
    expect(maxwellPanel).toContain("Incident medium, where light comes from");
    expect(maxwellPanel).toContain("Substrate medium, where light exits");
    expect(maxwellPanel).toContain("There is no 3D source-to-substrate distance in this solver.");
    expect(maxwellPanel).toContain("Planar Field Monitor");
    expect(maxwellPanel).toContain("Monitor CSV");
    expect(maxwellPanel).toContain("Design Foundry");
    expect(maxwellPanel).toContain("Apply Best");
    expect(maxwellPanel).toContain("Coating Stack Optimizer");
    expect(maxwellPanel).toContain("The optimizer tries selected materials, layer orders, and thicknesses.");
    expect(maxwellPanel).toContain("It does not search the internet or fetch new material data.");
    expect(maxwellPanel).toContain("Find Candidate Coatings");
    expect(maxwellPanel).toContain("Robust optimizer");
    expect(maxwellPanel).toContain("CoatingUncertaintyModel");
    expect(maxwellPanel).toContain("Shared deposition scale");
    expect(maxwellPanel).toContain("Shared offset + residual");
    expect(maxwellPanel).toContain("Independent P90");
    expect(maxwellPanel).toContain("formatUncertaintyReceipt");
    expect(maxwellPanel).toContain("Find Robust Coating Candidates");
    expect(maxwellPanel).toContain("Apply Robust Coating Candidate");
    expect(maxwellPanel).toContain("Robust Optimizer JSON");
    expect(maxwellPanel).toContain("Optimizer JSON");
    expect(maxwellPanel).toContain("Apply Coating Candidate");
    expect(maxwellPanel).not.toContain(">Coating Search<");
    expect(maxwellPanel).not.toContain(">Run Search<");
    expect(maxwellPanel).not.toContain(">Search JSON<");
    expect(maxwellPanel).not.toContain(">Apply Search<");
    expect(maxwellPanel).toContain("Tolerance Yield");
    expect(maxwellPanel).toContain("Yield JSON");
    expect(maxwellPanel).not.toMatch(/general 3D Maxwell solver ready|full 3D FEM Maxwell solver|arbitrary CAD Maxwell solved|production FEM\/BEM\/RCWA|3D Maxwell solve executed|full 3D Maxwell aperture solver|FDTD aperture solved|real thick lens solved|full stochastic 3D Maxwell simulated|real source statistics engine executed|certified calibration service|digital twin certified|manufacturing certified|EMVA compliant|pixel-level sensor stack executable|certified EMVA characterization executable|certified ISO 12233 result|Imatest-equivalent result|pure lens-only MTF certified|calibrated optical model fitting implemented|certified metrology report executable|lab accreditation workflow executable|hardware control implemented|AprilTag detector executable|ArUco detector executable/i);
  });

  it("keeps the visible app shell focused on L10.0 release-candidate review with L9.9 advisor packets, L9.8 examples, L9.7 intake, L9.6 consistency, L9.5 evidence packs, L9.4 routing, L9.3 RCWA, L9.2 FDTD, L8.9 external run ingestion, and earlier diagnostics still reachable", () => {
    const app = readFileSync(resolve(testDir, "App.tsx"), "utf8");
    const releaseCandidatePanel = readFileSync(resolve(testDir, "maxwell/ReleaseCandidatePanel.tsx"), "utf8");
    const advisorPacketPanel = readFileSync(resolve(testDir, "maxwell/AdvisorPacketPanel.tsx"), "utf8");
    const exampleLibraryPanel = readFileSync(resolve(testDir, "maxwell/ExampleLibraryPanel.tsx"), "utf8");
    const releaseCandidateCore = readFileSync(resolve(testDir, "../../../packages/core/src/maxwell/releaseCandidate.ts"), "utf8");
    const advisorPacketCore = readFileSync(resolve(testDir, "../../../packages/core/src/maxwell/advisorPacket.ts"), "utf8");
    const exampleLibraryCore = readFileSync(resolve(testDir, "../../../packages/core/src/maxwell/exampleLibrary.ts"), "utf8");
    const simulationBuilder = readFileSync(resolve(testDir, "maxwell/SimulationBuilderPanel.tsx"), "utf8");
    const simulationIntakeWizard = readFileSync(resolve(testDir, "../../../packages/core/src/maxwell/simulationIntakeWizard.ts"), "utf8");
    const crossSolverConsistency = readFileSync(resolve(testDir, "../../../packages/core/src/maxwell/crossSolverConsistency.ts"), "utf8");
    const solverRouter = readFileSync(resolve(testDir, "../../../packages/core/src/maxwell/solverRouter.ts"), "utf8");
    const solverEvidence = readFileSync(resolve(testDir, "../../../packages/core/src/maxwell/solverEvidence.ts"), "utf8");
    const fdtd2dSandbox = readFileSync(resolve(testDir, "maxwell/Fdtd2dSandboxPanel.tsx"), "utf8");
    const rcwaPanel = readFileSync(resolve(testDir, "maxwell/RcwaPreviewPanel.tsx"), "utf8");
    const fdtdReadme = readFileSync(resolve(testDir, "../../../tools/fdtd/README.md"), "utf8");
    const l88aSmoke = readFileSync(resolve(testDir, "../../../tools/fdtd/l88a_browser_smoke_code.js"), "utf8");
    const l90Smoke = readFileSync(resolve(testDir, "../../../tools/fdtd/l90_browser_smoke_code.js"), "utf8");
    const l91Smoke = readFileSync(resolve(testDir, "../../../tools/fdtd/l91_browser_smoke_code.js"), "utf8");
    const l92Smoke = readFileSync(resolve(testDir, "../../../tools/fdtd/l92_browser_smoke_code.js"), "utf8");
    const l93Smoke = readFileSync(resolve(testDir, "../../../tools/fdtd/l93_browser_smoke_code.js"), "utf8");
    const l94Smoke = readFileSync(resolve(testDir, "../../../tools/fdtd/l94_browser_smoke_code.js"), "utf8");
    const l95Smoke = readFileSync(resolve(testDir, "../../../tools/fdtd/l95_browser_smoke_code.js"), "utf8");
    const l96Smoke = readFileSync(resolve(testDir, "../../../tools/fdtd/l96_browser_smoke_code.js"), "utf8");
    const l97Smoke = readFileSync(resolve(testDir, "../../../tools/fdtd/l97_browser_smoke_code.js"), "utf8");
    const l98Smoke = readFileSync(resolve(testDir, "../../../tools/fdtd/l98_browser_smoke_code.js"), "utf8");
    const l99Smoke = readFileSync(resolve(testDir, "../../../tools/fdtd/l99_browser_smoke_code.js"), "utf8");
    const l100Smoke = readFileSync(resolve(testDir, "../../../tools/fdtd/l100_browser_smoke_code.js"), "utf8");
    const maxwellReturn = app.indexOf("return <MaxwellOnlyApp />;");
    const legacyWorkspace = app.indexOf('<main className="workspace">');

    expect(app).toContain('aria-label="Maxwell simulator"');
    expect(app).toContain("L10.0 Engineer Review Release Candidate / L9.9 Advisor Review Packet / L9.8 Example Library / L9.7 Build My Simulation");
    expect(app).toContain("Engineer Review RC + Advisor Review Packet + Example Library + Build My Simulation + Cross-Solver Consistency + RCWA Preview + 2D Maxwell Sandbox");
    expect(app).toContain("L10.0 RC packages the current evidence stack for review");
    expect(app).toContain("does not add solver physics, automatic correctness proof, certified validation, certified solver selection, or production RCWA/FDTD/FEM/BEM execution");
    expect(app).toContain("release");
    expect(app).toContain("Engineer Review RC");
    expect(app).toContain("advisor");
    expect(app).toContain("Advisor Review Packet");
    expect(app).toContain("examples");
    expect(app).toContain("Example Library");
    expect(app).toContain("intake");
    expect(app).toContain("Build My Simulation");
    expect(app).toContain("2D Maxwell Sandbox");
    expect(app).toContain("RCWA Preview");
    expect(app).toContain("Diagnostic Workbenches");
    expect(app).toContain("<SimulationBuilderPanel");
    expect(app).toContain("<Fdtd2dSandboxPanel");
    expect(app).toContain("<RcwaPreviewPanel />");
    expect(app).toContain("<MaxwellPanel />");
    expect(app).toContain("<ReleaseCandidatePanel");
    expect(app).toContain("<AdvisorPacketPanel");
    expect(app).toContain("<ExampleLibraryPanel");
    expect(app).toContain("initialWizardAnswers={exampleWizardAnswers}");
    expect(releaseCandidatePanel).toContain("L10.0 Engineer Review Release Candidate");
    expect(releaseCandidatePanel).toContain("L10.0 RC");
    expect(releaseCandidatePanel).toContain("Release Build Info");
    expect(releaseCandidatePanel).toContain("Suggested Review Path");
    expect(releaseCandidatePanel).toContain("15-minute engineer review");
    expect(releaseCandidatePanel).toContain("30-minute deep review");
    expect(releaseCandidatePanel).toContain("Full evidence review");
    expect(releaseCandidatePanel).toContain("Known Limitations / Capability Truth");
    expect(releaseCandidatePanel).toContain("Full Review Smoke Matrix");
    expect(releaseCandidatePanel).toContain("release_manifest.json");
    expect(releaseCandidatePanel).toContain("release_notes.md");
    expect(releaseCandidatePanel).toContain("review_checklist.md");
    expect(releaseCandidatePanel).toContain("known_limitations.md");
    expect(releaseCandidatePanel).toContain("public_demo_script.md");
    expect(releaseCandidatePanel).toContain("Export Full Advisor Packet");
    expect(releaseCandidatePanel).toContain("No arbitrary 3D Maxwell in browser");
    expect(releaseCandidatePanel).toContain("No production FDTD certification");
    expect(releaseCandidatePanel).toContain("No FEM/BEM");
    expect(releaseCandidatePanel).toContain("No production RCWA certification");
    expect(releaseCandidatePanel).toContain("No certified optical tolerancing");
    expect(releaseCandidatePanel).toContain("No full microscope digital twin");
    expect(releaseCandidatePanel).toContain("No manufacturing certification");
    expect(releaseCandidatePanel).toContain("No certified camera calibration");
    expect(releaseCandidateCore).toContain("L10.0 Engineer Review Release Candidate");
    expect(releaseCandidateCore).toContain("createReleaseCandidatePackage");
    expect(releaseCandidateCore).toContain("releaseCandidateExportFiles");
    expect(releaseCandidateCore).toContain("release_manifest.json");
    expect(releaseCandidateCore).toContain("release_notes.md");
    expect(releaseCandidateCore).toContain("review_checklist.md");
    expect(releaseCandidateCore).toContain("known_limitations.md");
    expect(releaseCandidateCore).toContain("public_demo_script.md");
    expect(releaseCandidateCore).toContain("v0.10.0-rc.1");
    expect(releaseCandidateCore).toContain("lighthouse-public-quality");
    expect(releaseCandidateCore).toContain("does not add a solver or new optical physics");
    expect(releaseCandidateCore).toContain("No arbitrary 3D Maxwell in browser");
    expect(advisorPacketPanel).toContain("L9.9 Advisor Review Packet / Evidence Dossier Generator");
    expect(advisorPacketPanel).toContain("Advisor Review Packet");
    expect(advisorPacketPanel).toContain("Packet preset");
    expect(advisorPacketPanel).toContain("Physics Sanity");
    expect(advisorPacketPanel).toContain("Surface Geometry");
    expect(advisorPacketPanel).toContain("Solver Credibility");
    expect(advisorPacketPanel).toContain("Full Current-State");
    expect(advisorPacketPanel).toContain("From L9.8 Example Library");
    expect(advisorPacketPanel).toContain("Completeness");
    expect(advisorPacketPanel).toContain("Claim Ledger");
    expect(advisorPacketPanel).toContain("Unsupported / Gap Table");
    expect(advisorPacketPanel).toContain("advisor_packet.md");
    expect(advisorPacketPanel).toContain("advisor_packet.json");
    expect(advisorPacketPanel).toContain("advisor_claim_ledger.csv");
    expect(advisorPacketPanel).toContain("advisor_evidence_table.csv");
    expect(advisorPacketPanel).toContain("advisor_gap_table.csv");
    expect(advisorPacketPanel).toContain("advisor_reproducibility_manifest.json");
    expect(advisorPacketPanel).toContain("Iteration count is not validation");
    expect(advisorPacketPanel).toContain("not certified validation");
    expect(advisorPacketCore).toContain("L9.9 Advisor Review Packet / Evidence Dossier Generator");
    expect(advisorPacketCore).toContain("advisorPacketPresets");
    expect(advisorPacketCore).toContain("createAdvisorReviewPacket");
    expect(advisorPacketCore).toContain("createAdvisorReviewPacketFromPreset");
    expect(advisorPacketCore).toContain("evaluateAdvisorPacketCompleteness");
    expect(advisorPacketCore).toContain("advisorPacketExportFiles");
    expect(advisorPacketCore).toContain("advisor_claim_ledger.csv");
    expect(advisorPacketCore).toContain("advisor_evidence_table.csv");
    expect(advisorPacketCore).toContain("advisor_gap_table.csv");
    expect(advisorPacketCore).toContain("advisor_reproducibility_manifest.json");
    expect(advisorPacketCore).toContain("Arbitrary 3D Maxwell runs in browser");
    expect(advisorPacketCore).toContain("FEM/BEM solver exists");
    expect(advisorPacketCore).toContain("not automatic correctness proof");
    expect(exampleLibraryPanel).toContain("L9.8 Guided Example Library / Known Experiment Pack");
    expect(exampleLibraryPanel).toContain("Search examples");
    expect(exampleLibraryPanel).toContain("Solver lane");
    expect(exampleLibraryPanel).toContain("Physics type");
    expect(exampleLibraryPanel).toContain("Difficulty");
    expect(exampleLibraryPanel).toContain("Runnable");
    expect(exampleLibraryPanel).toContain("External evidence");
    expect(exampleLibraryPanel).toContain("Analytic ref");
    expect(exampleLibraryPanel).toContain("Convergence");
    expect(exampleLibraryPanel).toContain("Measured data");
    expect(exampleLibraryPanel).toContain("Unsupported");
    expect(exampleLibraryCore).toContain("Load Example");
    expect(exampleLibraryCore).toContain("Open Wizard Answers");
    expect(exampleLibraryCore).toContain("Show Solver Route");
    expect(exampleLibraryCore).toContain("Generate Evidence Pack");
    expect(exampleLibraryCore).toContain("Open Consistency Bench");
    expect(exampleLibraryCore).toContain("Add to Engineering Evidence Campaign");
    expect(exampleLibraryCore).toContain("Export Example Report");
    expect(exampleLibraryPanel).toContain("example_report.md");
    expect(exampleLibraryPanel).toContain("example_report.json");
    expect(exampleLibraryPanel).toContain("example_registry.csv");
    expect(exampleLibraryPanel).toContain("example_scene_template.json");
    expect(exampleLibraryPanel).toContain("example_wizard_answers.json");
    expect(exampleLibraryPanel).toContain("not add solver physics, automatic correctness proof, certified validation, certified solver selection");
    expect(exampleLibraryCore).toContain("L9.8 Guided Example Library / Known Experiment Pack");
    expect(exampleLibraryCore).toContain("planar-air-glass-interface");
    expect(exampleLibraryCore).toContain("scalar-circular-aperture-airy");
    expect(exampleLibraryCore).toContain("rcwa-binary-grating");
    expect(exampleLibraryCore).toContain("fdtd2d-point-source");
    expect(exampleLibraryCore).toContain("external-transparent-finite-block");
    expect(exampleLibraryCore).toContain("diagnostic-slanted-edge-mtf");
    expect(exampleLibraryCore).toContain("evidence-engineering-campaign");
    expect(exampleLibraryCore).toContain("gap-unsupported-curved-material-lens");
    expect(exampleLibraryCore).toContain("createExampleLibraryRegistry");
    expect(exampleLibraryCore).toContain("filterExampleLibraryEntries");
    expect(exampleLibraryCore).toContain("loadExampleLibraryEntry");
    expect(exampleLibraryCore).toContain("exampleLibraryExportFiles");
    expect(exampleLibraryCore).toContain("promoteExampleToEngineeringEvidenceCampaign");
    expect(exampleLibraryCore).toContain("not automatic correctness proofs");
    expect(exampleLibraryCore).toContain("does not provide certified validation");
    expect(rcwaPanel).toContain("L9.3 In-Browser 1D RCWA Preview Solver");
    expect(rcwaPanel).toContain("Bounded 1D periodic solver preview only");
    expect(rcwaPanel).toContain("binary rectangular grating");
    expect(rcwaPanel).toContain("Run RCWA");
    expect(rcwaPanel).toContain("Run Harmonic Convergence");
    expect(rcwaPanel).toContain("Run No-Pattern TMM Check");
    expect(rcwaPanel).toContain("propagating/evanescent/near-cutoff");
    expect(rcwaPanel).toContain("rcwa_report.md");
    expect(rcwaPanel).toContain("rcwa_report.json");
    expect(rcwaPanel).toContain("rcwa_orders.csv");
    expect(rcwaPanel).toContain("rcwa_convergence.csv");
    expect(rcwaPanel).toContain("rcwa_tmm_consistency.csv");
    expect(rcwaPanel).toContain("not arbitrary 2D-periodic RCWA");
    expect(rcwaPanel).toContain("not production RCWA certification");
    expect(rcwaPanel).toContain("not arbitrary 3D Maxwell");
    expect(rcwaPanel).toContain("not FEM/BEM");
    expect(simulationIntakeWizard).toContain("L9.7 Solver Method Decision Wizard / Simulation Intake");
    expect(simulationIntakeWizard).toContain("simulationIntakeProblemOptions");
    expect(simulationIntakeWizard).toContain("simulationIntakeOutputOptions");
    expect(simulationIntakeWizard).toContain("simulationIntakeGeometryOptions");
    expect(simulationIntakeWizard).toContain("simulationIntakeMaterialOptions");
    expect(simulationIntakeWizard).toContain("simulationIntakeRigorOptions");
    expect(simulationIntakeWizard).toContain("createSimulationIntakeDecision");
    expect(simulationIntakeWizard).toContain("simulationIntakeDecisionReportMarkdown");
    expect(simulationIntakeWizard).toContain("simulationIntakeDecisionReportJson");
    expect(simulationIntakeWizard).toContain("simulationIntakeDecisionMatrixCsv");
    expect(simulationIntakeWizard).toContain("simulationIntakeGeneratedTemplateJson");
    expect(simulationIntakeWizard).toContain("simulationIntakeWizardAnswersJson");
    expect(simulationIntakeWizard).toContain("Create Scene Template");
    expect(simulationIntakeWizard).toContain("Open Recommended Solver");
    expect(simulationIntakeWizard).toContain("Generate Evidence Pack");
    expect(simulationIntakeWizard).toContain("Open Consistency Bench");
    expect(simulationIntakeWizard).toContain("Export Decision Report");
    expect(simulationIntakeWizard).toContain("Show Unsupported Gap Report");
    expect(simulationIntakeWizard).toContain("planar-tmm-coating-template");
    expect(simulationIntakeWizard).toContain("scalar-aperture-lens-template");
    expect(simulationIntakeWizard).toContain("rcwa-binary-grating-template");
    expect(simulationIntakeWizard).toContain("fdtd2d-sandbox-template");
    expect(simulationIntakeWizard).toContain("external-fdtd-builder-template");
    expect(simulationIntakeWizard).toContain("unsupported-gap-template");
    expect(simulationIntakeWizard).toContain("L9.7 is workflow guidance and simulation intake only; it does not add a solver or new optical physics.");
    expect(simulationIntakeWizard).toContain("does not certify solver selection");
    expect(simulationIntakeWizard).toContain("arbitrary 3D Maxwell");
    expect(simulationIntakeWizard).toContain("FEM");
    expect(simulationIntakeWizard).toContain("BEM");
    expect(simulationBuilder).toContain("L9.7 Build My Simulation + Solver Method Decision Wizard");
    expect(simulationBuilder).toContain("L9.7 Solver Method Decision Wizard / Simulation Intake");
    expect(simulationBuilder).toContain("L9.7 Build My Simulation wizard smoke preview");
    expect(simulationBuilder).toContain("Problem Type");
    expect(simulationBuilder).toContain("Desired Output");
    expect(simulationBuilder).toContain("Geometry");
    expect(simulationBuilder).toContain("Materials");
    expect(simulationBuilder).toContain("Rigor / Evidence Level");
    expect(simulationBuilder).toContain("Recommendation");
    expect(simulationBuilder).toContain("simulation_decision_report.md");
    expect(simulationBuilder).toContain("simulation_decision_report.json");
    expect(simulationBuilder).toContain("simulation_decision_matrix.csv");
    expect(simulationBuilder).toContain("generated_scene_template.json");
    expect(simulationBuilder).toContain("wizard_answers.json");
    expect(simulationBuilder).toContain("guided L9.7 simulation intake");
    expect(simulationBuilder).toContain("L9.7 is a deterministic decision wizard only; it does not add a new solver");
    expect(simulationBuilder).toContain("L9.6 Cross-Solver Consistency Bench");
    expect(simulationBuilder).toContain("L9.6 cross-solver consistency bench smoke preview");
    expect(simulationBuilder).toContain("PASS");
    expect(simulationBuilder).toContain("WARNING");
    expect(simulationBuilder).toContain("NOT COMPARABLE");
    expect(simulationBuilder).toContain("NEEDS EXTERNAL EVIDENCE");
    expect(simulationBuilder).toContain("cross_solver_consistency_report.md");
    expect(simulationBuilder).toContain("cross_solver_consistency_report.json");
    expect(simulationBuilder).toContain("consistency_metrics.csv");
    expect(simulationBuilder).toContain("solver_pair_residuals.csv");
    expect(simulationBuilder).toContain("consistency_assumptions.csv");
    expect(simulationBuilder).toContain("Import Bundled External FDTD Slab Fixture");
    expect(simulationBuilder).toContain("Export Consistency Report");
    expect(simulationBuilder).toContain("L9.5 Solver Router Evidence Auto-Pack / L9.4 Method Selection Matrix");
    expect(simulationBuilder).toContain("Solver Recommendation");
    expect(simulationBuilder).toContain("Evidence Pack");
    expect(crossSolverConsistency).toContain("L9.6 Cross-Solver Consistency Bench");
    expect(crossSolverConsistency).toContain("TMM vs RCWA no-pattern consistency");
    expect(crossSolverConsistency).toContain("CPU FDTD vs WebGPU FDTD parity");
    expect(crossSolverConsistency).toContain("Scalar aperture vs 2D FDTD diagnostic");
    expect(crossSolverConsistency).toContain("TMM/Fresnel vs external FDTD slab");
    expect(crossSolverConsistency).toContain("Absorber consistency");
    expect(crossSolverConsistency).toContain("RCWA vs external FDTD grating fixture");
    expect(crossSolverConsistency).toContain("tmm-rcwa-no-pattern");
    expect(crossSolverConsistency).toContain("fdtd-cpu-webgpu-parity");
    expect(crossSolverConsistency).toContain("scalar-fdtd-aperture");
    expect(crossSolverConsistency).toContain("tmm-external-fdtd-slab");
    expect(crossSolverConsistency).toContain("absorber-consistency");
    expect(crossSolverConsistency).toContain("NEEDS EXTERNAL EVIDENCE");
    expect(crossSolverConsistency).toContain("NOT COMPARABLE");
    expect(crossSolverConsistency).toContain("does not add a solver or new optical physics");
    expect(crossSolverConsistency).toContain("does not prove universal solver correctness");
    expect(solverEvidence).toContain("Generate Evidence Pack");
    expect(solverEvidence).toContain("Run In-Browser Checks");
    expect(solverEvidence).toContain("Export Evidence Bundle");
    expect(solverEvidence).toContain("Add to Engineering Evidence Campaign");
    expect(solverEvidence).toContain("Generate External Run Pack");
    expect(solverEvidence).toContain("Open Run Instructions");
    expect(solverEvidence).toContain("Import Results");
    expect(solverEvidence).toContain("Validate Receipts");
    expect(simulationBuilder).toContain("Use Current Builder Scene");
    expect(simulationBuilder).toContain("Load planar coating scene");
    expect(simulationBuilder).toContain("Load ideal aperture/lens scene");
    expect(simulationBuilder).toContain("Load binary grating scene");
    expect(simulationBuilder).toContain("Load finite 2D slice scene");
    expect(simulationBuilder).toContain("Load finite block/aperture scene");
    expect(simulationBuilder).toContain("Load unsupported curved material lens scene");
    expect(simulationBuilder).toContain("Recommended Solver");
    expect(simulationBuilder).toContain("Available Alternatives");
    expect(simulationBuilder).toContain("Validation Checks");
    expect(simulationBuilder).toContain("Route-Specific Next Actions");
    expect(simulationBuilder).toContain("Method Selection Matrix");
    expect(solverRouter).toContain("Open RCWA Preview Solver");
    expect(solverRouter).toContain("Send 2D Slice to FDTD Sandbox");
    expect(solverRouter).toContain("Export External FDTD Run Pack");
    expect(solverRouter).toContain("Open Engineering Evidence Campaign");
    expect(solverRouter).toContain("Show Unsupported Items");
    expect(simulationBuilder).toContain("solver_route_report.md");
    expect(simulationBuilder).toContain("solver_route_report.json");
    expect(simulationBuilder).toContain("solver_route_matrix.csv");
    expect(simulationBuilder).toContain("validation_plan.csv");
    expect(simulationBuilder).toContain("solver_evidence_task.md");
    expect(simulationBuilder).toContain("solver_evidence_task.json");
    expect(simulationBuilder).toContain("solver_evidence_artifacts.csv");
    expect(simulationBuilder).toContain("solver_evidence_validation_plan.csv");
    expect(solverEvidence).toContain("tmm_evidence_report.md");
    expect(solverEvidence).toContain("scalar_validation_report.md");
    expect(solverEvidence).toContain("rcwa_convergence.csv");
    expect(solverEvidence).toContain("fdtd2d_validation_report.md");
    expect(solverEvidence).toContain("external_fdtd_import_checklist.csv");
    expect(solverEvidence).toContain("unsupported_gap_report.md");
    expect(solverEvidence).toContain("promoteSolverEvidenceTaskToCampaign");
    expect(solverEvidence).toContain("L9.5 does not certify solver selection");
    expect(simulationBuilder).toContain("bounded L9.2 2D FDTD sandbox handoff");
    expect(simulationBuilder).toContain("The L9.6 bench compares overlapping solver lanes only and does not prove solver correctness");
    expect(simulationBuilder).toContain("The L9.5 evidence auto-pack generates route evidence tasks only, not automatic correctness proof");
    expect(simulationBuilder).toContain("The L9.4 router is method selection only");
    expect(simulationBuilder).toContain("The L9.2 sandbox is capped 2D TMz only with CPU reference stepping, optional WebGPU acceleration, parity/performance diagnostics");
    expect(simulationBuilder).toContain("Export 2D Slice to Maxwell Sandbox");
    expect(simulationBuilder).toContain("fdtd2d_sandbox_scene.json");
    expect(simulationBuilder).toContain("fdtd2d_sandbox_handoff.json");
    expect(simulationBuilder).toContain("real external FDTD run ingestion and reproducibility reports");
    expect(simulationBuilder).toContain("engineering evidence campaign dossiers");
    expect(simulationBuilder).toContain("diagnostic process/tolerance variation studies");
    expect(simulationBuilder).toContain("robust-design recommendations");
    expect(simulationBuilder).toContain("L8.8 Engineering Evidence Campaign");
    expect(simulationBuilder).toContain("Golden Evidence Pack / External FDTD Acceptance Campaign");
    expect(simulationBuilder).toContain("Load Bundled Golden Campaign");
    expect(simulationBuilder).toContain("Generate Engineer Review Dossier");
    expect(simulationBuilder).toContain("Golden Scenarios");
    expect(simulationBuilder).toContain("Capability Truth Table");
    expect(simulationBuilder).toContain("engineering_evidence_dossier.md");
    expect(simulationBuilder).toContain("scenario_summary.csv");
    expect(simulationBuilder).toContain("capability_truth_table.csv");
    expect(simulationBuilder).toContain("unsupported_items.csv");
    expect(simulationBuilder).toContain("L8.6 Process / Tolerance Runner");
    expect(simulationBuilder).toContain("L8.7 Robust Design Advisor");
    expect(simulationBuilder).toContain("Ranked Recommendations");
    expect(simulationBuilder).toContain("Baseline vs Candidate Comparison");
    expect(simulationBuilder).toContain("Tolerance Budget Advisor");
    expect(simulationBuilder).toContain("External FDTD Candidate Sweep");
    expect(simulationBuilder).toContain("Export Robust Design Report");
    expect(simulationBuilder).toContain("Export Candidate FDTD Sweep");
    expect(simulationBuilder).toContain("Import Bundled Candidate Sweep");
    expect(simulationBuilder).toContain("Apply Candidate");
    expect(simulationBuilder).toContain("robust_design_report.md");
    expect(simulationBuilder).toContain("candidate_table.csv");
    expect(simulationBuilder).toContain("recommendations.csv");
    expect(simulationBuilder).toContain("before_after_metrics.csv");
    expect(simulationBuilder).toContain("tolerance_budget.csv");
    expect(simulationBuilder).toContain("fdtd_candidate_sweep_manifest.json");
    expect(simulationBuilder).toContain("Load L8.6 Demo Tolerances");
    expect(simulationBuilder).toContain("Run One-at-a-Time");
    expect(simulationBuilder).toContain("Run Deterministic Grid");
    expect(simulationBuilder).toContain("Run Seeded Samples");
    expect(simulationBuilder).toContain("Add Source Wavelength");
    expect(simulationBuilder).toContain("Add Selected Thickness");
    expect(simulationBuilder).toContain("Export Tolerance Report");
    expect(simulationBuilder).toContain("Export FDTD Sweep Pack");
    expect(simulationBuilder).toContain("Import Bundled FDTD Sweep");
    expect(simulationBuilder).toContain("Variation Parameters");
    expect(simulationBuilder).toContain("Metrics / Requirements");
    expect(simulationBuilder).toContain("Sensitivity Ranking");
    expect(simulationBuilder).toContain("Run Table / Worst Cases");
    expect(simulationBuilder).toContain("External FDTD Variation Sweep");
    expect(simulationBuilder).toContain("tolerance_report.md");
    expect(simulationBuilder).toContain("tolerance_run_table.csv");
    expect(simulationBuilder).toContain("tolerance_sensitivity.csv");
    expect(simulationBuilder).toContain("fdtd_variation_sweep_manifest.json");
    expect(simulationBuilder).toContain("Multi-Element Optical Bench");
    expect(simulationBuilder).toContain("Element Inspector");
    expect(simulationBuilder).toContain("L8.5.1 element inspector direct editing smoke preview");
    expect(simulationBuilder).toContain("Numeric/text fields are the source of truth");
    expect(simulationBuilder).toContain("Interactive L8.5.1 x-z bench diagram");
    expect(simulationBuilder).toContain("aria-label={interactive ? `Drag ${item.label}`");
    expect(simulationBuilder).toContain("const draggable = interactive;");
    expect(simulationBuilder).toContain("Order and z-position");
    expect(simulationBuilder).toContain("Finite shape and transverse placement");
    expect(simulationBuilder).toContain("Inspector fields are exact source of truth");
    expect(simulationBuilder).toContain("L8.8a two-view interaction model smoke preview");
    expect(simulationBuilder).toContain("Inspect");
    expect(simulationBuilder).toContain("Edit Geometry");
    expect(simulationBuilder).toContain("Drag optical axis element z-only");
    expect(simulationBuilder).toContain("Drag finite surface geometry");
    expect(simulationBuilder).toContain("Keyboard nudge finite surface geometry");
    expect(simulationBuilder).toContain("Surface geometry warning visual summary");
    expect(simulationBuilder).toContain("Drag optical bench element");
    expect(simulationBuilder).toContain("Monitor before");
    expect(simulationBuilder).toContain("Monitor after");
    expect(simulationBuilder).toContain("Undo");
    expect(simulationBuilder).toContain("Redo");
    expect(simulationBuilder).toContain("Snap");
    expect(simulationBuilder).toContain("Grid -&gt; source -&gt; element chain -&gt; target -&gt; observation / monitors -&gt; validation report.");
    expect(simulationBuilder).toContain("Load L8.5 Bench");
    expect(simulationBuilder).toContain("Add slit");
    expect(simulationBuilder).toContain("Add ideal lens");
    expect(simulationBuilder).toContain("Add transparent block");
    expect(simulationBuilder).toContain("Add absorbing block");
    expect(simulationBuilder).toContain("Add reflective plate");
    expect(simulationBuilder).toContain("Add blocker");
    expect(simulationBuilder).toContain("Add wedge");
    expect(simulationBuilder).toContain("Add monitor");
    expect(simulationBuilder).toContain("Run Scalar Preview");
    expect(simulationBuilder).toContain("Import Bundled Multi-Element Fixture");
    expect(simulationBuilder).toContain("Export Multi-Element Scene");
    expect(simulationBuilder).toContain("Export External FDTD Chain");
    expect(simulationBuilder).toContain("Export Multi-Element Validation Report");
    expect(simulationBuilder).toContain("Element Chain");
    expect(simulationBuilder).toContain("X-Z Bench Cross-Section");
    expect(simulationBuilder).toContain("Solver Plan");
    expect(simulationBuilder).toContain("Monitor Stack");
    expect(simulationBuilder).toContain("Scalar Chain Preview");
    expect(simulationBuilder).toContain("External FDTD Chain Import");
    expect(simulationBuilder).toContain("multielement_scene.json");
    expect(simulationBuilder).toContain("solver_plan.json");
    expect(simulationBuilder).toContain("monitor_stack.csv");
    expect(simulationBuilder).toContain("multielement_validation_report.md");
    expect(simulationBuilder).toContain("multielement_validation_report.json");
    expect(simulationBuilder).toContain("multielement_metrics.csv");
    expect(simulationBuilder).toContain("Simulation Builder");
    expect(simulationBuilder).toContain("1 Grid");
    expect(simulationBuilder).toContain("2 Source");
    expect(simulationBuilder).toContain("3 Elements");
    expect(simulationBuilder).toContain("4 Target / Material");
    expect(simulationBuilder).toContain("5 Compute");
    expect(simulationBuilder).toContain("6 Validate");
    expect(simulationBuilder).toContain("Surface Geometry Elements");
    expect(simulationBuilder).toContain("Add Transparent Block");
    expect(simulationBuilder).toContain("Add Absorbing Block");
    expect(simulationBuilder).toContain("Add Reflective Plate");
    expect(simulationBuilder).toContain("Add Aperture/Blocker");
    expect(simulationBuilder).toContain("Add Tilted Wedge");
    expect(simulationBuilder).toContain("L8.3 Surface Geometry Interaction Starter Set");
    expect(simulationBuilder).toContain("L8.3 surface geometry palette smoke preview");
    expect(simulationBuilder).toContain("L8.3 x-z cross-section geometry smoke preview");
    expect(simulationBuilder).toContain("L8.3 transparent block field smoke preview");
    expect(simulationBuilder).toContain("L8.3 absorbing block field smoke preview");
    expect(simulationBuilder).toContain("L8.3 reflective plate smoke preview");
    expect(simulationBuilder).toContain("L8.3 aperture blocker diagnostic smoke preview");
    expect(simulationBuilder).toContain("L8.3 wedge warning smoke preview");
    expect(simulationBuilder).toContain("Load Transparent Block Fixture");
    expect(simulationBuilder).toContain("Load Absorbing Block Fixture");
    expect(simulationBuilder).toContain("Load Reflective Plate Fixture");
    expect(simulationBuilder).toContain("Load Aperture Blocker Fixture");
    expect(simulationBuilder).toContain("Load Wedge Fixture");
    expect(simulationBuilder).toContain("Export Surface Geometry Scene");
    expect(simulationBuilder).toContain("Export Surface Geometry Report");
    expect(simulationBuilder).toContain("surface_geometry_scene.json");
    expect(simulationBuilder).toContain("surface_geometry_validation_report.md");
    expect(simulationBuilder).toContain("surface_geometry_validation_report.json");
    expect(simulationBuilder).toContain("surface_geometry_metrics.csv");
    expect(simulationBuilder).toContain("L8.4 Aperture / Blocker Edge-Diffraction Validation");
    expect(simulationBuilder).toContain("Aperture / Blocker Validation");
    expect(simulationBuilder).toContain("Add Long Slit");
    expect(simulationBuilder).toContain("Add Circular Pinhole");
    expect(simulationBuilder).toContain("Add Rectangular Aperture");
    expect(simulationBuilder).toContain("Add Opaque Blocker");
    expect(simulationBuilder).toContain("Load Long Slit Fixture");
    expect(simulationBuilder).toContain("Load Circular Pinhole Fixture");
    expect(simulationBuilder).toContain("Load Rectangular Aperture Fixture");
    expect(simulationBuilder).toContain("Load Opaque Blocker Fixture");
    expect(simulationBuilder).toContain("Import Aperture Run");
    expect(simulationBuilder).toContain("Export Aperture Scene");
    expect(simulationBuilder).toContain("Export Aperture Dossier");
    expect(simulationBuilder).toContain("aperture_validation_scene.json");
    expect(simulationBuilder).toContain("aperture_validation_report.md");
    expect(simulationBuilder).toContain("aperture_metrics.csv");
    expect(simulationBuilder).toContain("aperture_profile.csv");
    expect(simulationBuilder).toContain("single-slit-sinc2");
    expect(simulationBuilder).toContain("airy-bessel");
    expect(simulationBuilder).toContain("aperture cells across");
    expect(simulationBuilder).toContain("blocked power");
    expect(simulationBuilder).toContain("L8.2 External FDTD / Field Maps");
    expect(simulationBuilder).toContain("L8.1 FDTD export readiness smoke preview");
    expect(simulationBuilder).toContain("L8.1 Meep script export smoke preview");
    expect(simulationBuilder).toContain("L8.1 field slice import smoke preview");
    expect(simulationBuilder).toContain("L8.1 FDTD flux validation smoke preview");
    expect(simulationBuilder).toContain("L8.1 unsupported geometry warning smoke preview");
    expect(simulationBuilder).toContain("L8.2 FDTD Verification Suite");
    expect(simulationBuilder).toContain("L8.2 FDTD benchmark suite smoke preview");
    expect(simulationBuilder).toContain("L8.2 sweep plan smoke preview");
    expect(simulationBuilder).toContain("L8.2 convergence import smoke preview");
    expect(simulationBuilder).toContain("L8.2 Fresnel convergence smoke preview");
    expect(simulationBuilder).toContain("L8.2 absorber convergence smoke preview");
    expect(simulationBuilder).toContain("L8.2 PML warning smoke preview");
    expect(simulationBuilder).toContain("Generate Sweep Plan");
    expect(simulationBuilder).toContain("Export Benchmark Pack");
    expect(simulationBuilder).toContain("Load Transparent Convergence Fixture");
    expect(simulationBuilder).toContain("Load Absorber Convergence Fixture");
    expect(simulationBuilder).toContain("Import Convergence");
    expect(simulationBuilder).toContain("Export Benchmark Dossier");
    expect(simulationBuilder).toContain("fdtd_benchmark_manifest.json");
    expect(simulationBuilder).toContain("fdtd_sweep_plan.json");
    expect(simulationBuilder).toContain("fdtd_expected_reference.json");
    expect(simulationBuilder).toContain("fdtd_benchmark_report.md");
    expect(simulationBuilder).toContain("fdtd_convergence_metrics.csv");
    expect(simulationBuilder).toContain("fdtd_run_table.csv");
    expect(simulationBuilder).toContain("Export FDTD Manifest");
    expect(simulationBuilder).toContain("Export Meep Script");
    expect(simulationBuilder).toContain("Import Field Run");
    expect(simulationBuilder).toContain("Load Transparent FDTD Fixture");
    expect(simulationBuilder).toContain("Load Absorbing FDTD Fixture");
    expect(simulationBuilder).toContain("fdtd_scene_manifest.json");
    expect(simulationBuilder).toContain("meep_scene.py");
    expect(simulationBuilder).toContain("fdtd_validation_report.md");
    expect(simulationBuilder).toContain("L8.9 Real External FDTD Run Ingestion");
    expect(simulationBuilder).toContain("L8.9 real external FDTD run ingestion smoke preview");
    expect(simulationBuilder).toContain("Export Real Run Pack");
    expect(simulationBuilder).toContain("Load Transparent Real Run Fixture");
    expect(simulationBuilder).toContain("Load Aperture Real Run Fixture");
    expect(simulationBuilder).toContain("Load Hash-Mismatch Fixture");
    expect(simulationBuilder).toContain("Import Real Run Bundle");
    expect(simulationBuilder).toContain("Promote to Engineering Evidence Campaign");
    expect(simulationBuilder).toContain("Accept Warnings + Promote");
    expect(simulationBuilder).toContain("Export Reproducibility Report");
    expect(simulationBuilder).toContain("scene_manifest.json");
    expect(simulationBuilder).toContain("expected_reference.json");
    expect(simulationBuilder).toContain("run_config.json");
    expect(simulationBuilder).toContain("material_receipts.json");
    expect(simulationBuilder).toContain("monitor_receipts.json");
    expect(simulationBuilder).toContain("reproduce.sh");
    expect(simulationBuilder).toContain("reproduce.ps1");
    expect(simulationBuilder).toContain("postprocess.py");
    expect(simulationBuilder).toContain("requirements-meep.txt");
    expect(simulationBuilder).toContain("reproducibility_report.md");
    expect(simulationBuilder).toContain("real_run_metrics.csv");
    expect(simulationBuilder).toContain("real_run_warnings.json");
    expect(simulationBuilder).toContain("Meep/Python stay local to the user machine");
    expect(simulationBuilder).toContain("External FDTD export/import only");
    expect(simulationBuilder).toContain("Production FDTD execution stays external");
    expect(simulationBuilder).toContain("Benchmark convergence evidence, not new in-browser physics.");
    expect(simulationBuilder).toContain("L8.0 optical-axis diagram smoke preview");
    expect(simulationBuilder).toContain("L8.0 surface validation smoke preview");
    expect(simulationBuilder).toContain("simulation_builder_scenario.json");
    expect(simulationBuilder).toContain("validation_report.md");
    expect(simulationBuilder).toContain("validation_report.json");
    expect(simulationBuilder).toContain("validation_metrics.csv");
    expect(simulationBuilder).toContain("Iteration count is not validation.");
    expect(simulationBuilder).toContain("arbitrary 3D Maxwell");
    expect(simulationBuilder).toContain("FDTD/FEM/BEM/RCWA execution");
    expect(simulationBuilder).toContain("manufacturing certification");
    expect(fdtd2dSandbox).toContain("L9.2 In-Browser 2D FDTD Maxwell Sandbox");
    expect(fdtd2dSandbox).toContain("Grid Safety / Memory Budget");
    expect(fdtd2dSandbox).toContain("Backend / WebGPU");
    expect(fdtd2dSandbox).toContain("Execution backend");
    expect(fdtd2dSandbox).toContain("CPU reference");
    expect(fdtd2dSandbox).toContain("WebGPU accelerated");
    expect(fdtd2dSandbox).toContain("Run CPU/GPU Parity Check");
    expect(fdtd2dSandbox).toContain("Run Performance Benchmark");
    expect(fdtd2dSandbox).toContain("Parity RMS Ez");
    expect(fdtd2dSandbox).toContain("steps/sec");
    expect(fdtd2dSandbox).toContain("Validation + Stability");
    expect(fdtd2dSandbox).toContain("CFL factor");
    expect(fdtd2dSandbox).toContain("NaN / Infinity");
    expect(fdtd2dSandbox).toContain("FDTD Validation Fixtures");
    expect(fdtd2dSandbox).toContain("Reference Checks");
    expect(fdtd2dSandbox).toContain("Run Bounded Convergence");
    expect(fdtd2dSandbox).toContain("Bounded 2D diagnostic sandbox only: TMz fields Ez, Hx, Hy.");
    expect(fdtd2dSandbox).toContain("not full 3D Maxwell");
    expect(fdtd2dSandbox).toContain("not production FDTD");
    expect(fdtd2dSandbox).toContain("not a replacement for external Meep/FDTD");
    expect(fdtd2dSandbox).toContain("Run N Steps");
    expect(fdtd2dSandbox).toContain("Export Validation Report");
    expect(fdtd2dSandbox).toContain("fdtd2d_validation_report.md");
    expect(fdtd2dSandbox).toContain("fdtd2d_validation_report.json");
    expect(fdtd2dSandbox).toContain("fdtd2d_backend_report.md");
    expect(fdtd2dSandbox).toContain("fdtd2d_backend_report.json");
    expect(fdtd2dSandbox).toContain("fdtd2d_parity.csv");
    expect(fdtd2dSandbox).toContain("fdtd2d_performance.csv");
    expect(fdtd2dSandbox).toContain("fdtd2d_convergence.csv");
    expect(fdtd2dSandbox).toContain("fdtd2d_stability_report.json");
    expect(fdtd2dSandbox).toContain("fdtd2d_energy_trace.csv");
    expect(fdtd2dSandbox).toContain("fdtd2d_monitor_trace.csv");
    expect(fdtd2dSandbox).toContain("field_snapshot.csv");
    expect(fdtd2dSandbox).toContain("monitor_trace.csv");
    expect(fdtd2dSandbox).toContain("energy_trace.csv");
    expect(fdtd2dSandbox).toContain("PEC Wall");
    expect(fdtd2dSandbox).toContain("Dielectric");
    expect(fdtd2dSandbox).toContain("Absorber");
    expect(fdtd2dSandbox).toContain("Point Symmetry");
    expect(fdtd2dSandbox).toContain("Slit");
    expect(fdtdReadme).toContain("L8.8a two-view interaction hardening");
    expect(fdtdReadme).toContain("l88a_browser_smoke_code.js");
    expect(fdtdReadme).toContain("L8.9 real-run packs");
    expect(fdtdReadme).toContain("l89_browser_smoke_code.js");
    expect(fdtdReadme).toContain("L9.0 sandbox smoke");
    expect(fdtdReadme).toContain("l90_browser_smoke_code.js");
    expect(fdtdReadme).toContain("L9.1 smoke artifacts");
    expect(fdtdReadme).toContain("l91_browser_smoke_code.js");
    expect(fdtdReadme).toContain("L9.2 smoke artifacts");
    expect(fdtdReadme).toContain("l92_browser_smoke_code.js");
    expect(fdtdReadme).toContain("L9.3 smoke artifacts");
    expect(fdtdReadme).toContain("l93_browser_smoke_code.js");
    expect(fdtdReadme).toContain("L9.4 smoke artifacts");
    expect(fdtdReadme).toContain("l94_browser_smoke_code.js");
    expect(fdtdReadme).toContain("L9.5 smoke artifacts");
    expect(fdtdReadme).toContain("l95_browser_smoke_code.js");
    expect(fdtdReadme).toContain("L9.6 smoke artifacts");
    expect(fdtdReadme).toContain("l96_browser_smoke_code.js");
    expect(fdtdReadme).toContain("L9.7 smoke artifacts");
    expect(fdtdReadme).toContain("l97_browser_smoke_code.js");
    expect(fdtdReadme).toContain("L9.8 smoke artifacts");
    expect(fdtdReadme).toContain("l98_browser_smoke_code.js");
    expect(fdtdReadme).toContain("L9.9 smoke artifacts");
    expect(fdtdReadme).toContain("l99_browser_smoke_code.js");
    expect(fdtdReadme).toContain("L10.0 release-candidate smoke artifacts");
    expect(fdtdReadme).toContain("l100_browser_smoke_code.js");
    expect(l88aSmoke).toContain("l88a-two-view-labels-smoke.png");
    expect(l88aSmoke).toContain("l88a-axis-z-drag-smoke.png");
    expect(l88aSmoke).toContain("l88a-xz-edit-handles-smoke.png");
    expect(l88aSmoke).toContain("l88a-warning-visuals-smoke.png");
    expect(l90Smoke).toContain("l90-fdtd-sandbox-grid-smoke.png");
    expect(l90Smoke).toContain("l90-fdtd-source-field-smoke.png");
    expect(l90Smoke).toContain("l90-fdtd-material-scatter-smoke.png");
    expect(l90Smoke).toContain("l90-fdtd-monitor-trace-smoke.png");
    expect(l90Smoke).toContain("l90-builder-to-sandbox-smoke.png");
    expect(l91Smoke).toContain("l91-fdtd-stability-dashboard-smoke.png");
    expect(l91Smoke).toContain("l91-fdtd-fixtures-smoke.png");
    expect(l91Smoke).toContain("l91-fresnel-absorber-reference-smoke.png");
    expect(l91Smoke).toContain("l91-grid-convergence-smoke.png");
    expect(l91Smoke).toContain("l91-validation-export-smoke.png");
    expect(l92Smoke).toContain("l92-backend-selector-smoke.png");
    expect(l92Smoke).toContain("l92-webgpu-status-smoke.png");
    expect(l92Smoke).toContain("l92-cpu-gpu-parity-smoke.png");
    expect(l92Smoke).toContain("l92-performance-benchmark-smoke.png");
    expect(l92Smoke).toContain("l92-fallback-cpu-smoke.png");
    expect(l93Smoke).toContain("l93-rcwa-default-grating-smoke.png");
    expect(l93Smoke).toContain("l93-rcwa-order-table-smoke.png");
    expect(l93Smoke).toContain("l93-rcwa-convergence-smoke.png");
    expect(l93Smoke).toContain("l93-rcwa-tmm-consistency-smoke.png");
    expect(l93Smoke).toContain("l93-rcwa-export-smoke.png");
    expect(l94Smoke).toContain("l94-solver-router-planar-smoke.png");
    expect(l94Smoke).toContain("l94-solver-router-rcwa-smoke.png");
    expect(l94Smoke).toContain("l94-solver-router-fdtd-smoke.png");
    expect(l94Smoke).toContain("l94-method-matrix-smoke.png");
    expect(l94Smoke).toContain("l94-route-report-smoke.png");
    expect(l95Smoke).toContain("l95-evidence-tmm-smoke.png");
    expect(l95Smoke).toContain("l95-evidence-scalar-smoke.png");
    expect(l95Smoke).toContain("l95-evidence-rcwa-smoke.png");
    expect(l95Smoke).toContain("l95-evidence-fdtd2d-smoke.png");
    expect(l95Smoke).toContain("l95-evidence-external-smoke.png");
    expect(l95Smoke).toContain("l95-evidence-unsupported-smoke.png");
    expect(l95Smoke).toContain("l95-evidence-promotion-smoke.png");
    expect(l96Smoke).toContain("l96-cross-solver-overview-smoke.png");
    expect(l96Smoke).toContain("l96-cross-solver-tmm-rcwa-smoke.png");
    expect(l96Smoke).toContain("l96-cross-solver-fdtd-parity-smoke.png");
    expect(l96Smoke).toContain("l96-cross-solver-external-slab-smoke.png");
    expect(l96Smoke).toContain("l96-cross-solver-report-export-smoke.png");
    expect(l96Smoke).toContain("TMM vs RCWA no-pattern consistency");
    expect(l96Smoke).toContain("CPU FDTD vs WebGPU FDTD parity");
    expect(l96Smoke).toContain("NEEDS EXTERNAL EVIDENCE");
    expect(l97Smoke).toContain("l97-wizard-start-smoke.png");
    expect(l97Smoke).toContain("l97-wizard-rcwa-route-smoke.png");
    expect(l97Smoke).toContain("l97-wizard-external-fdtd-route-smoke.png");
    expect(l97Smoke).toContain("l97-wizard-unsupported-gap-smoke.png");
    expect(l97Smoke).toContain("l97-wizard-decision-report-smoke.png");
    expect(l97Smoke).toContain("L9.7 Solver Method Decision Wizard / Simulation Intake");
    expect(l97Smoke).toContain("Build My Simulation");
    expect(l97Smoke).toContain("Problem Type");
    expect(l97Smoke).toContain("Desired Output");
    expect(l97Smoke).toContain("RCWA Preview Solver");
    expect(l97Smoke).toContain("External FDTD / Meep export-import");
    expect(l97Smoke).toContain("Unsupported gap report");
    expect(l97Smoke).toContain("simulation_decision_report.md");
    expect(l97Smoke).toContain("generated_scene_template.json");
    expect(l97Smoke).toContain("wizard_answers.json");
    expect(l98Smoke).toContain("l98-example-library-start-smoke.png");
    expect(l98Smoke).toContain("l98-airy-example-smoke.png");
    expect(l98Smoke).toContain("l98-rcwa-example-smoke.png");
    expect(l98Smoke).toContain("l98-fdtd-example-smoke.png");
    expect(l98Smoke).toContain("l98-external-fdtd-example-smoke.png");
    expect(l98Smoke).toContain("l98-gap-example-smoke.png");
    expect(l98Smoke).toContain("L9.8 Guided Example Library / Known Experiment Pack");
    expect(l98Smoke).toContain("Circular aperture Airy/Bessel");
    expect(l98Smoke).toContain("RCWA binary grating");
    expect(l98Smoke).toContain("2D FDTD point source");
    expect(l98Smoke).toContain("External FDTD transparent finite block");
    expect(l98Smoke).toContain("Unsupported curved material lens / arbitrary CAD gap");
    expect(l98Smoke).toContain("example_report.md");
    expect(l98Smoke).toContain("example_registry.csv");
    expect(l98Smoke).toContain("L9.7 Solver Method Decision Wizard / Simulation Intake");
    expect(l98Smoke).toContain("L9.3 In-Browser 1D RCWA Preview Solver");
    expect(l98Smoke).toContain("L9.2 In-Browser 2D FDTD Maxwell Sandbox");
    expect(l99Smoke).toContain("l99-advisor-packet-start-smoke.png");
    expect(l99Smoke).toContain("l99-physics-sanity-packet-smoke.png");
    expect(l99Smoke).toContain("l99-surface-geometry-packet-smoke.png");
    expect(l99Smoke).toContain("l99-claim-ledger-smoke.png");
    expect(l99Smoke).toContain("l99-completeness-check-smoke.png");
    expect(l99Smoke).toContain("l99-packet-export-smoke.png");
    expect(l99Smoke).toContain("L9.9 Advisor Review Packet / Evidence Dossier Generator");
    expect(l99Smoke).toContain("Physics Sanity");
    expect(l99Smoke).toContain("Surface Geometry");
    expect(l99Smoke).toContain("Solver Credibility");
    expect(l99Smoke).toContain("Full Current-State");
    expect(l99Smoke).toContain("advisor_packet.md");
    expect(l99Smoke).toContain("advisor_claim_ledger.csv");
    expect(l99Smoke).toContain("Arbitrary 3D Maxwell");
    expect(l99Smoke).toContain("L9.8 Guided Example Library / Known Experiment Pack");
    expect(l100Smoke).toContain("l100-rc-front-door-smoke.png");
    expect(l100Smoke).toContain("l100-review-path-smoke.png");
    expect(l100Smoke).toContain("l100-full-advisor-packet-smoke.png");
    expect(l100Smoke).toContain("l100-known-limitations-smoke.png");
    expect(l100Smoke).toContain("l100-release-manifest-smoke.png");
    expect(l100Smoke).toContain("l100-public-smoke-smoke.png");
    expect(l100Smoke).toContain("l100-release-smoke-trace.zip");
    expect(l100Smoke).toContain("L10.0 Engineer Review Release Candidate");
    expect(l100Smoke).toContain("Release Build Info");
    expect(l100Smoke).toContain("release_manifest.json");
    expect(l100Smoke).toContain("known_limitations.md");
    expect(l100Smoke).toContain("Export Full Advisor Packet");
    expect(l100Smoke).toContain("No arbitrary 3D Maxwell in browser");
    expect(l100Smoke).toContain("No production FDTD certification");
    expect(l100Smoke).toContain("No FEM/BEM");
    expect(l100Smoke).toContain("No production RCWA certification");
    expect(l100Smoke).toContain("No full microscope digital twin");
    expect(l100Smoke).toContain("No manufacturing certification");
    expect(l100Smoke).toContain("No certified camera calibration");
    expect(l100Smoke).toContain("L9.9 Advisor Review Packet / Evidence Dossier Generator");
    expect(l100Smoke).toContain("L9.8 Guided Example Library / Known Experiment Pack");
    expect(l100Smoke).toContain("L9.7 Solver Method Decision Wizard / Simulation Intake");
    expect(l100Smoke).toContain("L9.6 Cross-Solver Consistency Bench");
    expect(l100Smoke).toContain("L9.3 In-Browser 1D RCWA Preview Solver");
    expect(l100Smoke).toContain("L9.2 In-Browser 2D FDTD Maxwell Sandbox");
    expect(simulationBuilder).not.toMatch(/full 3D Maxwell execution is implemented|browser FDTD execution is available|FDTD execution is available in the browser|automatic correctness proof is complete|automatic correctness proof implemented|solver correctness certified|certified solver selection implemented|production RCWA certified|production FDTD certified|production RCWA\/FDTD certification implemented|FEM\/BEM route implemented|digital twin certified|manufacturing certification available/i);
    expect(maxwellReturn).toBeGreaterThan(0);
    expect(maxwellReturn).toBeLessThan(legacyWorkspace);
  });

  it("keeps L7.8.1 CI and bundle hygiene guardrails explicit", () => {
    const workflow = readFileSync(resolve(testDir, "../../../.github/workflows/deploy-pages.yml"), "utf8");
    const viteConfig = readFileSync(resolve(testDir, "../vite.config.ts"), "utf8");

    expect(workflow).toContain("actions/checkout@v6");
    expect(workflow).toContain("actions/setup-node@v6");
    expect(workflow).toContain("node-version: 24");
    expect(workflow).toContain("actions/upload-pages-artifact@v5");
    expect(workflow).toContain("actions/deploy-pages@v5");
    expect(workflow).not.toContain("actions/checkout@v4");
    expect(workflow).not.toContain("actions/setup-node@v4");
    expect(workflow).not.toContain("actions/deploy-pages@v4");
    expect(workflow).not.toContain("FORCE_JAVASCRIPT_ACTIONS_TO_NODE24");
    expect(viteConfig).toContain("manualChunks");
    expect(viteConfig).toContain("maxwell-panel");
    expect(viteConfig).toContain("core-measurement");
    expect(viteConfig).toContain("core-workspace");
    expect(viteConfig).toContain("core-maxwell");
    expect(viteConfig).not.toContain("core-shared");
    expect(viteConfig).not.toContain("chunkSizeWarningLimit");
  });
});
