import { describe, expect, it } from "vitest";
import { solverDisclosureFor } from "./App";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { fileURLToPath } from "node:url";

const testDir = fileURLToPath(new URL(".", import.meta.url));

describe("solver disclosure copy", () => {
  it("labels the L2 result as a 1D scalar slice without claiming a full PSF", () => {
    const disclosure = solverDisclosureFor("scalar.angularSpectrum.l2.1d");

    expect(disclosure.label).toBe("L2 scalar 1D field propagation");
    expect(disclosure.detail).toBe("1D transverse slice; not a full circular-aperture Airy disk");
    expect(`${disclosure.label} ${disclosure.detail}`).not.toMatch(/Airy disk simulated|full PSF simulated|full microscope image simulated/i);
  });

  it("labels L2.5 sample propagation without claiming a microscope image", () => {
    const disclosure = solverDisclosureFor("scalar.angularSpectrum.l2.1d", true);

    expect(disclosure.label).toBe("L2 scalar 1D sample propagation");
    expect(disclosure.detail).toBe("1D coherent transverse slice; not a full microscope image, full PSF, or Airy disk");
    expect(`${disclosure.label} ${disclosure.detail}`).not.toMatch(/Airy disk simulated|full PSF simulated|full microscope image simulated/i);
  });

  it("labels L3 as a coherent scalar 2D approximation without claiming complete microscope physics", () => {
    const disclosure = solverDisclosureFor("scalar.coherent.l3.2d");

    expect(disclosure.label).toBe("L3 coherent 2D scalar image approximation");
    expect(disclosure.detail).toContain("2D coherent scalar image-plane intensity approximation");
    expect(`${disclosure.label} ${disclosure.detail}`).not.toMatch(/full microscope image|true microscope simulation|incoherent imaging|fluorescence simulated|vector PSF|Maxwell solver/i);
  });

  it("labels L3.3 as a partial-coherence scalar approximation without certified microscope claims", () => {
    const disclosure = solverDisclosureFor("scalar.partialCoherent.l3.3.2d");

    expect(disclosure.label).toBe("L3.3 partial-coherence scalar brightfield approximation");
    expect(disclosure.detail).toContain("source-angle intensity averaging");
    expect(`${disclosure.label} ${disclosure.detail}`).not.toMatch(/true 3D simulation|certified microscope simulation|vector optics simulated|fluorescence simulated|Maxwell solver/i);
  });

  it("keeps measured-data UI copy away from certified calibration claims", () => {
    const importPanel = readFileSync(resolve(testDir, "measurement/ImageImportPanel.tsx"), "utf8");
    const calibrationPanel = readFileSync(resolve(testDir, "measurement/CalibrationPanel.tsx"), "utf8");
    const roiPanel = readFileSync(resolve(testDir, "measurement/RoiPanel.tsx"), "utf8");

    expect(`${importPanel}\n${calibrationPanel}\n${roiPanel}`).not.toMatch(/certified ISO|certified EMVA|clinical calibration|hardware calibration/i);
  });

  it("labels L3.4B compare/fit as diagnostic measured-vs-simulated workbench output", () => {
    const comparePanel = readFileSync(resolve(testDir, "measurement/ComparePanel.tsx"), "utf8");
    const fitPanel = readFileSync(resolve(testDir, "measurement/FitPanel.tsx"), "utf8");

    expect(comparePanel).toContain("measured-vs-simulated workbench");
    expect(comparePanel).toContain("Not certified ISO 12233, EMVA 1288, clinical, or hardware calibration");
    expect(fitPanel).toContain("diagnostic only");
    expect(`${comparePanel}\n${fitPanel}`).not.toMatch(/certified ISO 12233 calibration|certified EMVA 1288 calibration|clinical calibration service|hardware calibration service/i);
  });

  it("labels L6.7 measured-vs-simulated lab data workbench over planar/scalar execution without claiming certified calibration or arbitrary 3D EM", () => {
    const maxwellPanel = readFileSync(resolve(testDir, "maxwell/MaxwellPanel.tsx"), "utf8");
    const explainability = readFileSync(resolve(testDir, "explainabilityContent.ts"), "utf8");
    const explainComponents = readFileSync(resolve(testDir, "explainability/Explainability.tsx"), "utf8");

    expect(maxwellPanel).toContain("L6.7 Measured-vs-Simulated Lab Data Workbench");
    expect(maxwellPanel).toContain("measured CSV/image import, calibration, ROI, residual metrics, diagnostic fit, saved studies, sweeps, markers, comparisons, capabilities, and exports over the existing planar/scalar engines");
    expect(maxwellPanel).toContain("PlanarTmmBackend and scalar validation remain the executable scope; diagnostic measured comparison is not certified calibration, sensor simulation, a digital twin, or 3D Maxwell/FDTD/FEM/BEM/RCWA execution");
    expect(maxwellPanel).toContain("Explain mode");
    expect(maxwellPanel).toContain("Show all explanations");
    expect(maxwellPanel).toContain("Under the hood: Airy/Bessel reference");
    expect(maxwellPanel).toContain("Under the hood: numerical propagation");
    expect(maxwellPanel).toContain("Under the hood: thin lens phase");
    expect(maxwellPanel).toContain("Under the hood: ExternalFdtdBackend");
    expect(explainComponents).toContain('role="tooltip"');
    expect(explainComponents).toContain("aria-describedby");
    expect(explainComponents).toContain("Escape");
    expect(explainComponents).toContain("ShowAllExplanationsDrawer");
    expect(explainComponents).not.toContain("title=");
    expect(explainability).toContain("validation.source.wavelength");
    expect(explainability).toContain("validation.analyticReference.airyBessel");
    expect(explainability).toContain("validation.numericalPropagation.huygensFresnel");
    expect(explainability).toContain("validation.residualMap");
    expect(explainability).toContain("validation.spatialBench");
    expect(explainability).toContain("validation.whereMeasured");
    expect(explainability).toContain("validation.radialOverlay");
    expect(explainability).toContain("validation.residualCurve");
    expect(explainability).toContain("validation.lens.thinLensPhase");
    expect(explainability).toContain("validation.lens.airyRadius");
    expect(explainability).toContain("validation.lens.focusMetric");
    expect(explainability).toContain("coherence.mode");
    expect(explainability).toContain("coherence.coherentFields");
    expect(explainability).toContain("coherence.incoherentIntensities");
    expect(explainability).toContain("coherence.gamma");
    expect(explainability).toContain("coherence.visibility");
    expect(explainability).toContain("coherence.formula");
    expect(explainability).toContain("coherence.orderSpacing");
    expect(explainability).toContain("coherence.slitGeometry");
    expect(explainability).toContain("backend.planarTmm");
    expect(explainability).toContain("backend.externalFdtdScaffold");
    expect(explainability).toContain("coating.planarStack");
    expect(explainability).toContain("coating.incidentMedium");
    expect(explainability).toContain("coating.substrateMedium");
    expect(explainability).toContain("coating.rtaMeasurementLocation");
    expect(explainability).toContain("coating.fieldMonitorLocation");
    expect(explainability).toContain("optimizer.coatingStack");
    expect(explainability).toContain("optimizer.candidateMaterials");
    expect(explainability).toContain("optimizer.applyCandidate");
    expect(explainability).toContain("coating.provenanceReceipt");
    expect(explainability).toContain("coating.reflectance");
    expect(explainability).toContain("robust.p90Score");
    expect(explainability).toContain("robust.sampleReduction");
    expect(explainability).toContain("No full 3D Maxwell, FDTD, FEM, BEM, RCWA");
    expect(maxwellPanel).toContain("L6.0 does not execute 3D Maxwell solves.");
    expect(maxwellPanel).toContain("It defines the 3D problem/result contract and external-backend export scaffold only.");
    expect(maxwellPanel).toContain("Validation Bench: spatial optical layout");
    expect(maxwellPanel).toContain("Coating Stack Workbench: planar layer model");
    expect(maxwellPanel).toContain("z = 0 mm Source");
    expect(maxwellPanel).toContain("Aperture / Slit / Lens");
    expect(maxwellPanel).toContain("Light direction");
    expect(maxwellPanel).toContain("Incident medium");
    expect(maxwellPanel).toContain("Where is this measured?");
    expect(maxwellPanel).toContain("Validation Bench");
    expect(maxwellPanel).toContain("Study Manager");
    expect(maxwellPanel).toContain("Save Study");
    expect(maxwellPanel).toContain("Load Study");
    expect(maxwellPanel).toContain("Duplicate Study");
    expect(maxwellPanel).toContain("Delete Study");
    expect(maxwellPanel).toContain("Export Study Bundle");
    expect(maxwellPanel).toContain("Import Study Bundle");
    expect(maxwellPanel).toContain("Copy Shareable URL");
    expect(maxwellPanel).toContain("Parameter Sweep Runner");
    expect(maxwellPanel).toContain("coherence gamma");
    expect(maxwellPanel).toContain("validation wavelength");
    expect(maxwellPanel).toContain("observation z");
    expect(maxwellPanel).toContain("slit width");
    expect(maxwellPanel).toContain("double-slit separation");
    expect(maxwellPanel).toContain("thin-lens defocus");
    expect(maxwellPanel).toContain("coating wavelength");
    expect(maxwellPanel).toContain("Run Sweep");
    expect(maxwellPanel).toContain("Cancel Sweep");
    expect(maxwellPanel).toContain("Sweep JSON");
    expect(maxwellPanel).toContain("Sweep Markdown");
    expect(maxwellPanel).toContain("Sweep CSV");
    expect(maxwellPanel).toContain("Measurement Tools");
    expect(maxwellPanel).toContain("Pin Crosshair");
    expect(maxwellPanel).toContain("Peak Finder");
    expect(maxwellPanel).toContain("Minimum Finder");
    expect(maxwellPanel).toContain("Profile CSV");
    expect(maxwellPanel).toContain("Measured-vs-Simulated");
    expect(maxwellPanel).toContain("Generate Synthetic CSV");
    expect(maxwellPanel).toContain("Import Measured CSV");
    expect(maxwellPanel).toContain("Import PNG/JPEG/CSV");
    expect(maxwellPanel).toContain("Compare Measured vs Simulated");
    expect(maxwellPanel).toContain("Run Diagnostic Fit");
    expect(maxwellPanel).toContain("Save Comparison Study");
    expect(maxwellPanel).toContain("Export Comparison Report");
    expect(maxwellPanel).toContain("diagnostic alignment and residual analysis, not certified instrument calibration");
    expect(maxwellPanel).toContain("Run Comparison");
    expect(maxwellPanel).toContain("Compare Gamma 1 vs Gamma 0");
    expect(maxwellPanel).toContain("Compare Selected Runs");
    expect(maxwellPanel).toContain("Comparison Markdown");
    expect(maxwellPanel).toContain("Comparison CSV");
    expect(maxwellPanel).toContain("Capabilities Matrix");
    expect(maxwellPanel).toContain("3D Maxwell solve");
    expect(maxwellPanel).toContain("not-implemented");
    expect(maxwellPanel).toContain("scaffold-only");
    expect(maxwellPanel).toContain("l67CapabilitiesMatrix");
    expect(maxwellPanel).toContain("compareMeasuredToSimulatedProfile");
    expect(maxwellPanel).toContain("parseMeasuredCsvProfile");
    expect(maxwellPanel).toContain("runL67DiagnosticFit");
    expect(maxwellPanel).toContain("measuredComparisonBundleJson");
    expect(maxwellPanel).toContain("createStudySnapshot");
    expect(maxwellPanel).toContain("studyBundleJson");
    expect(maxwellPanel).toContain("runCoherenceGammaSweep");
    expect(maxwellPanel).toContain("runCircularObservationZSweep");
    expect(maxwellPanel).toContain("runThinLensDefocusSweep");
    expect(maxwellPanel).toContain("compareStudyRuns");
    expect(maxwellPanel).toContain("createFieldMarker");
    expect(maxwellPanel).toContain("Physics exam sequence");
    expect(maxwellPanel).toContain("Circular pinhole Airy/Bessel");
    expect(maxwellPanel).toContain("Long single slit sinc^2");
    expect(maxwellPanel).toContain("Double slit / grating orders");
    expect(maxwellPanel).toContain("Ideal thin lens focal plane");
    expect(maxwellPanel).toContain("Coherence Demonstrator");
    expect(maxwellPanel).toContain("Coherence Demonstrator: double slit");
    expect(maxwellPanel).toContain("Degree of coherence |gamma12|");
    expect(maxwellPanel).toContain("Coherent fields");
    expect(maxwellPanel).toContain("Incoherent intensities");
    expect(maxwellPanel).toContain("Partial coherence");
    expect(maxwellPanel).toContain("Fringe visibility V");
    expect(maxwellPanel).toContain("V = (Imax - Imin) / (Imax + Imin)");
    expect(maxwellPanel).toContain("I = |U1|^2 + |U2|^2 + 2 Re(gamma12 U1 U2*)");
    expect(maxwellPanel).toContain("Gamma 1.00");
    expect(maxwellPanel).toContain("Gamma 0.50");
    expect(maxwellPanel).toContain("Gamma 0.00");
    expect(maxwellPanel).toContain("Coherent Map");
    expect(maxwellPanel).toContain("Incoherent Map");
    expect(maxwellPanel).toContain("Partial-Coherence Map");
    expect(maxwellPanel).toContain("Interference-Term Map");
    expect(maxwellPanel).toContain("Run Coherence Demo");
    expect(maxwellPanel).toContain("Coherence JSON");
    expect(maxwellPanel).toContain("Coherence Markdown");
    expect(maxwellPanel).toContain("Coherence CSV");
    expect(maxwellPanel).toContain("Coherence Demonstrator: double slit");
    expect(maxwellPanel).toContain("Advisor Review Mode");
    expect(maxwellPanel).toContain("Run Advisor Review");
    expect(maxwellPanel).toContain("Advisor Markdown");
    expect(maxwellPanel).toContain("Advisor JSON");
    expect(maxwellPanel).toContain("Advisor CSV");
    expect(maxwellPanel).toContain("y1 ~= 5.00 mm");
    expect(maxwellPanel).toContain("orders every 5.00 mm");
    expect(maxwellPanel).toContain("Slit JSON");
    expect(maxwellPanel).toContain("Slit Markdown");
    expect(maxwellPanel).toContain("Ideal thin lens focal-plane validation");
    expect(maxwellPanel).toContain("r1 ~= 1.22 lambda f / D = 61 um");
    expect(maxwellPanel).toContain("Lens phase");
    expect(maxwellPanel).toContain("Pupil D");
    expect(maxwellPanel).toContain("Numerical Focal Map");
    expect(maxwellPanel).toContain("Analytic Airy Map");
    expect(maxwellPanel).toContain("Focus Scan");
    expect(maxwellPanel).toContain("Run Lens Benchmark");
    expect(maxwellPanel).toContain("Lens JSON");
    expect(maxwellPanel).toContain("Lens Markdown");
    expect(maxwellPanel).toContain("Lens CSV");
    expect(maxwellPanel).toContain("runThinLensFocalValidation");
    expect(maxwellPanel).toContain("thinLensFocalValidationJson");
    expect(maxwellPanel).toContain("thinLensFocalValidationCsv");
    expect(maxwellPanel).toContain("runCoherenceDemonstrator");
    expect(maxwellPanel).toContain("coherenceDemonstratorJson");
    expect(maxwellPanel).toContain("coherenceDemonstratorCsv");
    expect(maxwellPanel).toContain("runSlitOrderValidation");
    expect(maxwellPanel).toContain("runAdvisorValidationReview");
    expect(maxwellPanel).toContain("slitOrderValidationJson");
    expect(maxwellPanel).toContain("advisorValidationReviewMarkdown");
    expect(maxwellPanel).toContain("Circular pinhole Airy/Bessel");
    expect(maxwellPanel).toContain("Circular aperture, not long slit");
    expect(maxwellPanel).toContain("hand-checkable scalar diffraction benchmarks with numerical results, analytic references, residuals, and report exports");
    expect(maxwellPanel).toContain("Computation mode");
    expect(maxwellPanel).toContain("Analytic Airy reference");
    expect(maxwellPanel).toContain("Numerical scalar propagation");
    expect(maxwellPanel).toContain("Compare numerical vs analytic");
    expect(maxwellPanel).toContain("Map grid");
    expect(maxwellPanel).toContain("Aperture radial");
    expect(maxwellPanel).toContain("Aperture angular");
    expect(maxwellPanel).toContain("Numerical Intensity Map");
    expect(maxwellPanel).toContain("Analytic Reference Map");
    expect(maxwellPanel).toContain("Residual Map");
    expect(maxwellPanel).toContain("Residual Curve");
    expect(maxwellPanel).toContain("Measured first min");
    expect(maxwellPanel).toContain("Finite-plane energy check");
    expect(maxwellPanel).toContain("Expected first Airy minimum");
    expect(maxwellPanel).toContain("Warning: first minimum is outside the 10 mm x 10 mm observation plane.");
    expect(maxwellPanel).toContain("Observation z");
    expect(maxwellPanel).toContain("Run Comparison");
    expect(maxwellPanel).toContain("Validation JSON");
    expect(maxwellPanel).toContain("Validation Markdown");
    expect(maxwellPanel).toContain("runCircularApertureValidation");
    expect(maxwellPanel).toContain("circularApertureValidationPipeline");
    expect(maxwellPanel).toContain("circularApertureValidationJson");
    expect(maxwellPanel).toContain("circularApertureValidationMarkdown");
    expect(maxwellPanel).toContain("Active solver backend");
    expect(maxwellPanel).toContain("PlanarTmmBackend");
    expect(maxwellPanel).toContain("ExternalFdtdBackend");
    expect(maxwellPanel).toContain("Future 3D Backends");
    expect(maxwellPanel).toContain("Scaffolded, not executable");
    expect(maxwellPanel).toContain("schema/export only in L6.0");
    expect(maxwellPanel).toContain("Export 3D FDTD Scaffold");
    expect(maxwellPanel).toContain("createMinimalMaxwellScene3D");
    expect(maxwellPanel).toContain("exportExternalFdtdScaffold");
    expect(maxwellPanel).toContain("externalFdtdSolverReceipt");
    expect(maxwellPanel).toContain("FEM/FDTD/BEM/RCWA");
    expect(maxwellPanel).toContain("solverBackend: run.solverBackend");
    expect(maxwellPanel).toContain("createMaterialCatalog");
    expect(maxwellPanel).toContain("listCatalogMaterials");
    expect(maxwellPanel).toContain("runCoatingSearch");
    expect(maxwellPanel).toContain("runRobustCoatingSearch");
    expect(maxwellPanel).toContain("runCoatingStack");
    expect(maxwellPanel).toContain("runCoatingSweep");
    expect(maxwellPanel).toContain("runCoatingDesignFoundry");
    expect(maxwellPanel).toContain("runCoatingYieldAnalysis");
    expect(maxwellPanel).toContain("serializeCoatingStackDesign");
    expect(maxwellPanel).toContain("parseMaterialImportJson");
    expect(maxwellPanel).toContain("Material Library");
    expect(maxwellPanel).toContain("MaterialPassport");
    expect(maxwellPanel).toContain("Template JSON");
    expect(maxwellPanel).toContain("Example Pack");
    expect(maxwellPanel).toContain("Example setup");
    expect(maxwellPanel).toContain("Incident medium, where light comes from");
    expect(maxwellPanel).toContain("Substrate medium, where light exits");
    expect(maxwellPanel).toContain("There is no 3D source-to-substrate distance in this solver.");
    expect(maxwellPanel).toContain("Planar Field Monitor");
    expect(maxwellPanel).toContain("Monitor CSV");
    expect(maxwellPanel).toContain("Design Foundry");
    expect(maxwellPanel).toContain("Apply Best");
    expect(maxwellPanel).toContain("Coating Stack Optimizer");
    expect(maxwellPanel).toContain("The optimizer tries selected materials, layer orders, and thicknesses.");
    expect(maxwellPanel).toContain("It does not search the internet or fetch new material data.");
    expect(maxwellPanel).toContain("Find Candidate Coatings");
    expect(maxwellPanel).toContain("Robust optimizer");
    expect(maxwellPanel).toContain("CoatingUncertaintyModel");
    expect(maxwellPanel).toContain("Shared deposition scale");
    expect(maxwellPanel).toContain("Shared offset + residual");
    expect(maxwellPanel).toContain("Independent P90");
    expect(maxwellPanel).toContain("formatUncertaintyReceipt");
    expect(maxwellPanel).toContain("Find Robust Coating Candidates");
    expect(maxwellPanel).toContain("Apply Robust Coating Candidate");
    expect(maxwellPanel).toContain("Robust Optimizer JSON");
    expect(maxwellPanel).toContain("Optimizer JSON");
    expect(maxwellPanel).toContain("Apply Coating Candidate");
    expect(maxwellPanel).not.toContain(">Coating Search<");
    expect(maxwellPanel).not.toContain(">Run Search<");
    expect(maxwellPanel).not.toContain(">Search JSON<");
    expect(maxwellPanel).not.toContain(">Apply Search<");
    expect(maxwellPanel).toContain("Tolerance Yield");
    expect(maxwellPanel).toContain("Yield JSON");
    expect(maxwellPanel).not.toMatch(/general 3D Maxwell solver ready|full 3D FEM Maxwell solver|arbitrary CAD Maxwell solved|production FEM\/BEM\/RCWA|3D Maxwell solve executed|full 3D Maxwell aperture solver|FDTD aperture solved|real thick lens solved|full stochastic 3D Maxwell simulated|real source statistics engine executed|certified calibration service|digital twin certified|manufacturing certified/i);
  });

  it("keeps the visible app shell Maxwell-only", () => {
    const app = readFileSync(resolve(testDir, "App.tsx"), "utf8");
    const maxwellReturn = app.indexOf("return <MaxwellOnlyApp />;");
    const legacyWorkspace = app.indexOf('<main className="workspace">');

    expect(app).toContain('aria-label="Maxwell simulator"');
    expect(app).toContain("PlanarTmmBackend + Measured Workbench");
    expect(app).toContain("L6.7 Measured-vs-Simulated Lab Data Workbench");
    expect(app).toContain("diagnostic measured comparison, executable planar backend, saved studies, sweeps, measurements, comparisons, capabilities matrix, study bundle exports");
    expect(maxwellReturn).toBeGreaterThan(0);
    expect(maxwellReturn).toBeLessThan(legacyWorkspace);
  });
});
