import { describe, expect, it } from "vitest";
import { solverDisclosureFor } from "./App";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { fileURLToPath } from "node:url";

const testDir = fileURLToPath(new URL(".", import.meta.url));

describe("solver disclosure copy", () => {
  it("labels the L2 result as a 1D scalar slice without claiming a full PSF", () => {
    const disclosure = solverDisclosureFor("scalar.angularSpectrum.l2.1d");

    expect(disclosure.label).toBe("L2 scalar 1D field propagation");
    expect(disclosure.detail).toBe("1D transverse slice; not a full circular-aperture Airy disk");
    expect(`${disclosure.label} ${disclosure.detail}`).not.toMatch(/Airy disk simulated|full PSF simulated|full microscope image simulated/i);
  });

  it("labels L2.5 sample propagation without claiming a microscope image", () => {
    const disclosure = solverDisclosureFor("scalar.angularSpectrum.l2.1d", true);

    expect(disclosure.label).toBe("L2 scalar 1D sample propagation");
    expect(disclosure.detail).toBe("1D coherent transverse slice; not a full microscope image, full PSF, or Airy disk");
    expect(`${disclosure.label} ${disclosure.detail}`).not.toMatch(/Airy disk simulated|full PSF simulated|full microscope image simulated/i);
  });

  it("labels L3 as a coherent scalar 2D approximation without claiming complete microscope physics", () => {
    const disclosure = solverDisclosureFor("scalar.coherent.l3.2d");

    expect(disclosure.label).toBe("L3 coherent 2D scalar image approximation");
    expect(disclosure.detail).toContain("2D coherent scalar image-plane intensity approximation");
    expect(`${disclosure.label} ${disclosure.detail}`).not.toMatch(/full microscope image|true microscope simulation|incoherent imaging|fluorescence simulated|vector PSF|Maxwell solver/i);
  });

  it("labels L3.3 as a partial-coherence scalar approximation without certified microscope claims", () => {
    const disclosure = solverDisclosureFor("scalar.partialCoherent.l3.3.2d");

    expect(disclosure.label).toBe("L3.3 partial-coherence scalar brightfield approximation");
    expect(disclosure.detail).toContain("source-angle intensity averaging");
    expect(`${disclosure.label} ${disclosure.detail}`).not.toMatch(/true 3D simulation|certified microscope simulation|vector optics simulated|fluorescence simulated|Maxwell solver/i);
  });

  it("keeps measured-data UI copy away from certified calibration claims", () => {
    const importPanel = readFileSync(resolve(testDir, "measurement/ImageImportPanel.tsx"), "utf8");
    const calibrationPanel = readFileSync(resolve(testDir, "measurement/CalibrationPanel.tsx"), "utf8");
    const roiPanel = readFileSync(resolve(testDir, "measurement/RoiPanel.tsx"), "utf8");

    expect(`${importPanel}\n${calibrationPanel}\n${roiPanel}`).not.toMatch(/certified ISO|certified EMVA|clinical calibration|hardware calibration/i);
  });

  it("labels L3.4B compare/fit as diagnostic measured-vs-simulated workbench output", () => {
    const comparePanel = readFileSync(resolve(testDir, "measurement/ComparePanel.tsx"), "utf8");
    const fitPanel = readFileSync(resolve(testDir, "measurement/FitPanel.tsx"), "utf8");

    expect(comparePanel).toContain("measured-vs-simulated workbench");
    expect(comparePanel).toContain("Not certified ISO 12233, EMVA 1288, clinical, or hardware calibration");
    expect(fitPanel).toContain("diagnostic only");
    expect(`${comparePanel}\n${fitPanel}`).not.toMatch(/certified ISO 12233 calibration|certified EMVA 1288 calibration|clinical calibration service|hardware calibration service/i);
  });

  it("labels L7.8 detector round-trip workflow over planar/scalar execution without claiming certified calibration, sensor-stack EM, arbitrary 3D EM, browser-native detector decoding, calibrated optical fitting, or lab metrology", () => {
    const maxwellPanel = readFileSync(resolve(testDir, "maxwell/MaxwellPanel.tsx"), "utf8");
    const explainability = readFileSync(resolve(testDir, "explainabilityContent.ts"), "utf8");
    const explainComponents = readFileSync(resolve(testDir, "explainability/Explainability.tsx"), "utf8");

    expect(maxwellPanel).toContain("L7.8 Detector Round-Trip Acceptance Pack / Real Detector Bridge");
    expect(maxwellPanel).toContain("diagnostic detector round-trip acceptance over board export, optional external detector helper output, JSON/CSV import, receipt/hash validation, ID matching, geometry fit, session QA, and evidence exports");
    expect(maxwellPanel).toContain("External Detector Bridge");
    expect(maxwellPanel).toContain("External Detector Round Trip");
    expect(maxwellPanel).toContain("Run Round-Trip Acceptance");
    expect(maxwellPanel).toContain("Export Round-Trip Evidence");
    expect(maxwellPanel).toContain("L7.8 detector round-trip wizard smoke preview");
    expect(maxwellPanel).toContain("L7.8 detector round-trip acceptance smoke preview");
    expect(maxwellPanel).toContain("L7.8 detector round-trip export smoke preview");
    expect(maxwellPanel).toContain("roundtrip_report.md");
    expect(maxwellPanel).toContain("roundtrip_report.json");
    expect(maxwellPanel).toContain("roundtrip_metrics.csv");
    expect(maxwellPanel).toContain("roundtrip_warnings.json");
    expect(maxwellPanel).toContain("OpenCV ChArUco detector JSON import");
    expect(maxwellPanel).toContain("Detector marker CSV import");
    expect(maxwellPanel).toContain("Export Board for Detector");
    expect(maxwellPanel).toContain("Load Example Detector JSON");
    expect(maxwellPanel).toContain("Load Example Detector CSV");
    expect(maxwellPanel).toContain("Import OpenCV ChArUco Detector Output");
    expect(maxwellPanel).toContain("Detector version");
    expect(maxwellPanel).toContain("Dictionary");
    expect(maxwellPanel).toContain("Parameters");
    expect(maxwellPanel).toContain("Import Detector CSV");
    expect(maxwellPanel).toContain("Validate Detection");
    expect(maxwellPanel).toContain("Compare Synthetic vs Imported");
    expect(maxwellPanel).toContain("Run Detector Geometry Fit");
    expect(maxwellPanel).toContain("Add Detector Frame to Session QA");
    expect(maxwellPanel).toContain("Export Detector Bridge Report");
    expect(maxwellPanel).toContain("Save Detector Bridge Study");
    expect(maxwellPanel).toContain("L7.7 detector bridge import smoke preview");
    expect(maxwellPanel).toContain("L7.7 detector receipt smoke preview");
    expect(maxwellPanel).toContain("L7.7 detector comparison smoke preview");
    expect(maxwellPanel).toContain("L7.7 detector fit handoff smoke preview");
    expect(maxwellPanel).toContain("L7.7 detector session handoff smoke preview");
    expect(maxwellPanel).toContain("detector_bridge_report.md");
    expect(maxwellPanel).toContain("detector_bridge_report.json");
    expect(maxwellPanel).toContain("imported_detections.csv");
    expect(maxwellPanel).toContain("detector_comparison.csv");
    expect(maxwellPanel).toContain("browser-native OpenCV.js/ArUco detector execution is not implemented");
    expect(maxwellPanel).toContain("Fiducial Board / ChArUco-style Target");
    expect(maxwellPanel).toContain("Diagnostic ChArUco-style synthetic fiducial board");
    expect(maxwellPanel).toContain("not OpenCV-compatible");
    expect(maxwellPanel).toContain("AprilTag decoding is not implemented");
    expect(maxwellPanel).toContain("Generate Fiducial Board");
    expect(maxwellPanel).toContain("Generate Synthetic Detections");
    expect(maxwellPanel).toContain("Load Example Fiducial JSON");
    expect(maxwellPanel).toContain("Import Fiducial JSON");
    expect(maxwellPanel).toContain("Match Fiducial IDs");
    expect(maxwellPanel).toContain("Reject Selected Marker");
    expect(maxwellPanel).toContain("Accept Selected Marker");
    expect(maxwellPanel).toContain("Move Selected Corner");
    expect(maxwellPanel).toContain("Relabel Selected Marker");
    expect(maxwellPanel).toContain("Run Fiducial Similarity Fit");
    expect(maxwellPanel).toContain("Run Fiducial Affine Fit");
    expect(maxwellPanel).toContain("Export Fiducial Bundle");
    expect(maxwellPanel).toContain("Add Fiducial Frame to Session QA");
    expect(maxwellPanel).toContain("Save Fiducial Study");
    expect(maxwellPanel).toContain("L7.5 fiducial board generator smoke preview");
    expect(maxwellPanel).toContain("L7.5 fiducial detection overlay smoke preview");
    expect(maxwellPanel).toContain("L7.5 partial-view coverage smoke preview");
    expect(maxwellPanel).toContain("L7.5 fiducial fit results smoke preview");
    expect(maxwellPanel).toContain("L7.5 fiducial session handoff smoke preview");
    expect(maxwellPanel).toContain("board_manifest.json");
    expect(maxwellPanel).toContain("fiducial_detection_report.md");
    expect(maxwellPanel).toContain("fiducial_detection_report.json");
    expect(maxwellPanel).toContain("matched_points.csv");
    expect(maxwellPanel).toContain("fitFiducialBoardDetection");
    expect(maxwellPanel).toContain("generateFiducialBoard");
    expect(maxwellPanel).toContain("generateSyntheticFiducialDetection");
    expect(maxwellPanel).toContain("parseFiducialDetectionJson");
    expect(maxwellPanel).toContain("applyFiducialManualEdits");
    expect(maxwellPanel).toContain("l74FrameFromFiducialFit");
    expect(maxwellPanel).toContain("l76CapabilitiesMatrix");
    expect(maxwellPanel).toContain("L7.8 detector round-trip acceptance reports are the executable scope");
    expect(maxwellPanel).toContain("browser-native OpenCV.js/ArUco detector execution, AprilTag decoding");
    expect(maxwellPanel).toContain("L7.4 Batch Measurement Session + Repeatability QA");
    expect(maxwellPanel).toContain("Batch Session Manifest");
    expect(maxwellPanel).toContain("Repeatability Thresholds");
    expect(maxwellPanel).toContain("Load Example Session Manifest");
    expect(maxwellPanel).toContain("Run Session QA");
    expect(maxwellPanel).toContain("Export Session QA");
    expect(maxwellPanel).toContain("Save Session Study");
    expect(maxwellPanel).toContain("Frame Review");
    expect(maxwellPanel).toContain("Aggregate Metrics");
    expect(maxwellPanel).toContain("Outlier Table");
    expect(maxwellPanel).toContain("Trend Plot");
    expect(maxwellPanel).toContain("session_report.md");
    expect(maxwellPanel).toContain("session_report.json");
    expect(maxwellPanel).toContain("frame_metrics.csv");
    expect(maxwellPanel).toContain("session_metrics.csv");
    expect(maxwellPanel).toContain("outliers.csv");
    expect(maxwellPanel).toContain("warnings.json");
    expect(maxwellPanel).toContain("parseL74SessionManifestCsv");
    expect(maxwellPanel).toContain("l74SyntheticFramesFromManifest");
    expect(maxwellPanel).toContain("runL74SessionQa");
    expect(maxwellPanel).toContain("sessionReportMarkdown");
    expect(maxwellPanel).toContain("frameMetricsCsv");
    expect(maxwellPanel).toContain("sessionMetricsCsv");
    expect(maxwellPanel).toContain("outliersCsv");
    expect(maxwellPanel).toContain("L7.4 diagnostic batch measurement session QA/repeatability aggregation");
    expect(maxwellPanel).toContain("certified metrology reports, lab-accredited metrology, lab accreditation workflows, hardware control");
    expect(maxwellPanel).toContain("L7.3 Measured Target Detection and ROI Hardening");
    expect(maxwellPanel).toContain("Import or generate measured target images, adjust ROI, auto-detect dot grids, correct points manually, fit L7.2 geometry, and export detection confidence reports.");
    expect(maxwellPanel).toContain("Measured Image Detection");
    expect(maxwellPanel).toContain("Detection Confidence Report");
    expect(maxwellPanel).toContain("Use Target As Measured Image");
    expect(maxwellPanel).toContain("Import Target Image");
    expect(maxwellPanel).toContain("Auto Detect");
    expect(maxwellPanel).toContain("Clear Detection");
    expect(maxwellPanel).toContain("Move Selected Point");
    expect(maxwellPanel).toContain("Reject Selected Point");
    expect(maxwellPanel).toContain("Run Geometry Fit");
    expect(maxwellPanel).toContain("Export Detection Report");
    expect(maxwellPanel).toContain("Save Detection Study");
    expect(maxwellPanel).toContain("ROI-limited dot-grid detection");
    expect(maxwellPanel).toContain("Checkerboard automatic detection is scaffold-only; AprilTag/ArUco fiducials are not implemented in L7.3.");
    expect(maxwellPanel).toContain("L7.2 generated geometric calibration target");
    expect(maxwellPanel).toContain("Geometric Calibration / Distortion Workbench");
    expect(maxwellPanel).toContain("Generate Dot/Grid Target");
    expect(maxwellPanel).toContain("Import Point CSV");
    expect(maxwellPanel).toContain("Import Point File");
    expect(maxwellPanel).toContain("Run Similarity Fit");
    expect(maxwellPanel).toContain("Run Affine Fit");
    expect(maxwellPanel).toContain("Run Radial Fit");
    expect(maxwellPanel).toContain("Compare Geometry");
    expect(maxwellPanel).toContain("Export Geometric Bundle");
    expect(maxwellPanel).toContain("Save Geometric Study");
    expect(maxwellPanel).toContain("Pixel scale");
    expect(maxwellPanel).toContain("Rotation");
    expect(maxwellPanel).toContain("Shear");
    expect(maxwellPanel).toContain("RMS residual");
    expect(maxwellPanel).toContain("Max residual");
    expect(maxwellPanel).toContain("Radial k1");
    expect(maxwellPanel).toContain("Residual vector map");
    expect(maxwellPanel).toContain("Corrected / undistorted points");
    expect(maxwellPanel).toContain("diagnostic 2D image geometry only; not certified camera calibration, lab metrology, full 3D pose/stereo calibration");
    expect(maxwellPanel).toContain("l76CapabilitiesMatrix");
    expect(maxwellPanel).toContain("generateGeometricCalibrationTarget");
    expect(maxwellPanel).toContain("fitGeometricCalibration");
    expect(maxwellPanel).toContain("parseGeometricPointCsv");
    expect(maxwellPanel).toContain("compareGeometricCalibrations");
    expect(maxwellPanel).toContain("geometricCalibrationReportMarkdown");
    expect(maxwellPanel).toContain("geometricResidualsCsv");
    expect(maxwellPanel).toContain("distortionMapCsv");
    expect(maxwellPanel).toContain("detectMeasuredTargetPoints");
    expect(maxwellPanel).toContain("pointSetFromDetection");
    expect(maxwellPanel).toContain("applyDetectionManualEdits");
    expect(maxwellPanel).toContain("detectionReportMarkdown");
    expect(maxwellPanel).toContain("detectedPointsCsv");
    expect(maxwellPanel).toContain("rejectedPointsCsv");
    expect(maxwellPanel).toContain("L7.1 Focus + Field MTF Qualification Workbench");
    expect(maxwellPanel).toContain("Run synthetic or current-frame focus MTF sweeps, map field ROIs, apply diagnostic thresholds");
    expect(maxwellPanel).toContain("Run Focus Sweep");
    expect(maxwellPanel).toContain("Import Current MTF Into Sweep");
    expect(maxwellPanel).toContain("Run Field Map");
    expect(maxwellPanel).toContain("Run Qualification");
    expect(maxwellPanel).toContain("Export Qualification Bundle");
    expect(maxwellPanel).toContain("Save Qualification Study");
    expect(maxwellPanel).toContain("Compare Focus Field MTF");
    expect(maxwellPanel).toContain("MTF50 vs focus");
    expect(maxwellPanel).toContain("Worst-field ROI");
    expect(maxwellPanel).toContain("L7.1 measured vs simulated focus/field MTF");
    expect(maxwellPanel).toContain("not ISO 12233 certification, Imatest-equivalent testing, calibrated optical model fitting");
    expect(maxwellPanel).toContain("L7.0 Slanted-Edge / Resolution Target MTF Workbench");
    expect(maxwellPanel).toContain("Import a batch manifest, normalize existing diagnostic frame metrics, aggregate repeatability and drift");
    expect(maxwellPanel).toContain("L7.2 diagnostic 2D geometric calibration/distortion/pixel-scale workflows, L7.3 diagnostic ROI-limited dot-grid measured target detection, L7.4 diagnostic batch measurement session QA/repeatability aggregation, L7.5 diagnostic synthetic fiducial board generation/imported detection matching/manual correction/session handoff, L7.7 external detector JSON/CSV import, detector receipt validation, comparison, report exports, and L7.8 detector round-trip acceptance reports are the executable scope");
    expect(maxwellPanel).toContain("Generate/import slanted-edge targets, compute ESF/LSF/SFR-MTF, compare measured vs simulated MTF, and sanity-check line-pair contrast.");
    expect(maxwellPanel).toContain("Generate Slanted Edge Target");
    expect(maxwellPanel).toContain("Run Slanted-Edge MTF");
    expect(maxwellPanel).toContain("Compare Blur Response");
    expect(maxwellPanel).toContain("Generate Line-Pair Target");
    expect(maxwellPanel).toContain("Export MTF Bundle");
    expect(maxwellPanel).toContain("Save MTF Study");
    expect(maxwellPanel).toContain("Send Camera DN Frame to MTF");
    expect(maxwellPanel).toContain("MTF50 / MTF10");
    expect(maxwellPanel).toContain("Measured vs Simulated MTF");
    expect(maxwellPanel).toContain("Line-Pair Target");
    expect(maxwellPanel).toContain("Camera Calibration Workbench");
    expect(maxwellPanel).toContain("This is an EMVA-inspired diagnostic calibration workflow.");
    expect(maxwellPanel).toContain("It is not an EMVA 1288 certification, ISO-certified calibration, lab-accredited camera characterization, sensor-stack EM, digital twin, or full 3D Maxwell/FDTD/FEM/BEM/RCWA execution.");
    expect(maxwellPanel).toContain("Calibration CSV summary");
    expect(maxwellPanel).toContain("Load Example Calibration CSV");
    expect(maxwellPanel).toContain("Load Example With photons_per_pixel");
    expect(maxwellPanel).toContain("Import Calibration CSV");
    expect(maxwellPanel).toContain("Run Photon-Transfer Fit");
    expect(maxwellPanel).toContain("Apply Calibrated Camera Profile");
    expect(maxwellPanel).toContain("Export Calibration Bundle");
    expect(maxwellPanel).toContain("Save Calibration Study");
    expect(maxwellPanel).toContain("Effective QE");
    expect(maxwellPanel).toContain("Residual RMS / max");
    expect(maxwellPanel).toContain("Linearity / SNR mismatch");
    expect(maxwellPanel).toContain("Camera / Sensor-Lite");
    expect(maxwellPanel).toContain("Convert selected simulated optical intensity into photons, electrons, DN, SNR, saturation, histogram, and line-profile evidence.");
    expect(maxwellPanel).toContain("Camera/Sensor-Lite converts an existing simulated intensity map into synthetic detector readout");
    expect(maxwellPanel).toContain("does not model pixel-level electromagnetic absorption, microlenses, color filters, charge diffusion, semiconductor transport, a calibrated sensor stack, certified EMVA compliance, digital twin behavior, or 3D Maxwell/FDTD/FEM/BEM/RCWA execution");
    expect(maxwellPanel).toContain("Pixel pitch um");
    expect(maxwellPanel).toContain("Sensor width px");
    expect(maxwellPanel).toContain("Sensor height px");
    expect(maxwellPanel).toContain("Quantum efficiency QE");
    expect(maxwellPanel).toContain("Exposure time ms");
    expect(maxwellPanel).toContain("Photon flux scale");
    expect(maxwellPanel).toContain("Full well e-");
    expect(maxwellPanel).toContain("Read noise e- RMS");
    expect(maxwellPanel).toContain("Dark current e-/px/s");
    expect(maxwellPanel).toContain("ADC bit depth");
    expect(maxwellPanel).toContain("Conversion gain DN/e-");
    expect(maxwellPanel).toContain("Black level DN");
    expect(maxwellPanel).toContain("Noise mode");
    expect(maxwellPanel).toContain("Generate Camera Output");
    expect(maxwellPanel).toContain("Saturate Exposure");
    expect(maxwellPanel).toContain("Export Camera Report");
    expect(maxwellPanel).toContain("Send synthetic camera image to Measured-vs-Simulated");
    expect(maxwellPanel).toContain("Save Camera Study");
    expect(maxwellPanel).toContain("Mean / peak photons");
    expect(maxwellPanel).toContain("Mean / peak electrons");
    expect(maxwellPanel).toContain("Mean / peak DN");
    expect(maxwellPanel).toContain("Saturation fraction");
    expect(maxwellPanel).toContain("Mean / peak SNR");
    expect(maxwellPanel).toContain("Dynamic range estimate");
    expect(maxwellPanel).toContain("Explain mode");
    expect(maxwellPanel).toContain("Show all explanations");
    expect(maxwellPanel).toContain("Under the hood: Airy/Bessel reference");
    expect(maxwellPanel).toContain("Under the hood: numerical propagation");
    expect(maxwellPanel).toContain("Under the hood: thin lens phase");
    expect(maxwellPanel).toContain("Under the hood: ExternalFdtdBackend");
    expect(explainComponents).toContain('role="tooltip"');
    expect(explainComponents).toContain("aria-describedby");
    expect(explainComponents).toContain("Escape");
    expect(explainComponents).toContain("ShowAllExplanationsDrawer");
    expect(explainComponents).not.toContain("title=");
    expect(explainability).toContain("validation.source.wavelength");
    expect(explainability).toContain("validation.analyticReference.airyBessel");
    expect(explainability).toContain("validation.numericalPropagation.huygensFresnel");
    expect(explainability).toContain("validation.residualMap");
    expect(explainability).toContain("validation.spatialBench");
    expect(explainability).toContain("validation.whereMeasured");
    expect(explainability).toContain("validation.radialOverlay");
    expect(explainability).toContain("validation.residualCurve");
    expect(explainability).toContain("validation.lens.thinLensPhase");
    expect(explainability).toContain("validation.lens.airyRadius");
    expect(explainability).toContain("validation.lens.focusMetric");
    expect(explainability).toContain("coherence.mode");
    expect(explainability).toContain("coherence.coherentFields");
    expect(explainability).toContain("coherence.incoherentIntensities");
    expect(explainability).toContain("coherence.gamma");
    expect(explainability).toContain("coherence.visibility");
    expect(explainability).toContain("coherence.formula");
    expect(explainability).toContain("coherence.orderSpacing");
    expect(explainability).toContain("coherence.slitGeometry");
    expect(explainability).toContain("backend.planarTmm");
    expect(explainability).toContain("backend.externalFdtdScaffold");
    expect(explainability).toContain("coating.planarStack");
    expect(explainability).toContain("coating.incidentMedium");
    expect(explainability).toContain("coating.substrateMedium");
    expect(explainability).toContain("coating.rtaMeasurementLocation");
    expect(explainability).toContain("coating.fieldMonitorLocation");
    expect(explainability).toContain("optimizer.coatingStack");
    expect(explainability).toContain("optimizer.candidateMaterials");
    expect(explainability).toContain("optimizer.applyCandidate");
    expect(explainability).toContain("coating.provenanceReceipt");
    expect(explainability).toContain("coating.reflectance");
    expect(explainability).toContain("robust.p90Score");
    expect(explainability).toContain("robust.sampleReduction");
    expect(explainability).toContain("No full 3D Maxwell, FDTD, FEM, BEM, RCWA");
    expect(maxwellPanel).toContain("L6.0 does not execute 3D Maxwell solves.");
    expect(maxwellPanel).toContain("It defines the 3D problem/result contract and external-backend export scaffold only.");
    expect(maxwellPanel).toContain("Validation Bench: spatial optical layout");
    expect(maxwellPanel).toContain("Coating Stack Workbench: planar layer model");
    expect(maxwellPanel).toContain("z = 0 mm Source");
    expect(maxwellPanel).toContain("Aperture / Slit / Lens");
    expect(maxwellPanel).toContain("Light direction");
    expect(maxwellPanel).toContain("Incident medium");
    expect(maxwellPanel).toContain("Where is this measured?");
    expect(maxwellPanel).toContain("Validation Bench");
    expect(maxwellPanel).toContain("Study Manager");
    expect(maxwellPanel).toContain("Save Study");
    expect(maxwellPanel).toContain("Load Study");
    expect(maxwellPanel).toContain("Duplicate Study");
    expect(maxwellPanel).toContain("Delete Study");
    expect(maxwellPanel).toContain("Export Study Bundle");
    expect(maxwellPanel).toContain("Import Study Bundle");
    expect(maxwellPanel).toContain("Copy Shareable URL");
    expect(maxwellPanel).toContain("Parameter Sweep Runner");
    expect(maxwellPanel).toContain("coherence gamma");
    expect(maxwellPanel).toContain("validation wavelength");
    expect(maxwellPanel).toContain("observation z");
    expect(maxwellPanel).toContain("slit width");
    expect(maxwellPanel).toContain("double-slit separation");
    expect(maxwellPanel).toContain("thin-lens defocus");
    expect(maxwellPanel).toContain("coating wavelength");
    expect(maxwellPanel).toContain("Run Sweep");
    expect(maxwellPanel).toContain("Cancel Sweep");
    expect(maxwellPanel).toContain("Sweep JSON");
    expect(maxwellPanel).toContain("Sweep Markdown");
    expect(maxwellPanel).toContain("Sweep CSV");
    expect(maxwellPanel).toContain("Measurement Tools");
    expect(maxwellPanel).toContain("Pin Crosshair");
    expect(maxwellPanel).toContain("Peak Finder");
    expect(maxwellPanel).toContain("Minimum Finder");
    expect(maxwellPanel).toContain("Profile CSV");
    expect(maxwellPanel).toContain("Measured-vs-Simulated");
    expect(maxwellPanel).toContain("Generate Synthetic CSV");
    expect(maxwellPanel).toContain("Import Measured CSV");
    expect(maxwellPanel).toContain("Import PNG/JPEG/CSV");
    expect(maxwellPanel).toContain("Compare Measured vs Simulated");
    expect(maxwellPanel).toContain("Run Diagnostic Fit");
    expect(maxwellPanel).toContain("Save Comparison Study");
    expect(maxwellPanel).toContain("Export Comparison Report");
    expect(maxwellPanel).toContain("diagnostic alignment and residual analysis, not certified instrument calibration");
    expect(maxwellPanel).toContain("Run Comparison");
    expect(maxwellPanel).toContain("Compare Gamma 1 vs Gamma 0");
    expect(maxwellPanel).toContain("Compare Selected Runs");
    expect(maxwellPanel).toContain("Comparison Markdown");
    expect(maxwellPanel).toContain("Comparison CSV");
    expect(maxwellPanel).toContain("Capabilities Matrix");
    expect(maxwellPanel).toContain("3D Maxwell solve");
    expect(maxwellPanel).toContain("not-implemented");
    expect(maxwellPanel).toContain("scaffold-only");
    expect(maxwellPanel).toContain("l76CapabilitiesMatrix");
    expect(maxwellPanel).toContain("runSyntheticFocusSweepMtf");
    expect(maxwellPanel).toContain("runFieldMtfMap");
    expect(maxwellPanel).toContain("qualifyFocusFieldMtf");
    expect(maxwellPanel).toContain("compareFocusFieldMtf");
    expect(maxwellPanel).toContain("runSlantedEdgeMtf");
    expect(maxwellPanel).toContain("generateSlantedEdgeTarget");
    expect(maxwellPanel).toContain("generateLinePairTarget");
    expect(maxwellPanel).toContain("compareMtfRuns");
    expect(maxwellPanel).toContain("runCameraCalibration");
    expect(maxwellPanel).toContain("parseCameraCalibrationCsv");
    expect(maxwellPanel).toContain("cameraCalibrationReportBundleJson");
    expect(maxwellPanel).toContain("runCameraSensorLite");
    expect(maxwellPanel).toContain("cameraReportBundleJson");
    expect(maxwellPanel).toContain("cameraRunToMeasuredDataset");
    expect(maxwellPanel).toContain("cameraMetricsCsv");
    expect(maxwellPanel).toContain("cameraProfileCsv");
    expect(maxwellPanel).toContain("cameraHistogramCsv");
    expect(maxwellPanel).toContain("compareMeasuredToSimulatedProfile");
    expect(maxwellPanel).toContain("parseMeasuredCsvProfile");
    expect(maxwellPanel).toContain("runL67DiagnosticFit");
    expect(maxwellPanel).toContain("measuredComparisonBundleJson");
    expect(maxwellPanel).toContain("createStudySnapshot");
    expect(maxwellPanel).toContain("studyBundleJson");
    expect(maxwellPanel).toContain("runCoherenceGammaSweep");
    expect(maxwellPanel).toContain("runCircularObservationZSweep");
    expect(maxwellPanel).toContain("runThinLensDefocusSweep");
    expect(maxwellPanel).toContain("compareStudyRuns");
    expect(maxwellPanel).toContain("createFieldMarker");
    expect(maxwellPanel).toContain("Physics exam sequence");
    expect(maxwellPanel).toContain("Circular pinhole Airy/Bessel");
    expect(maxwellPanel).toContain("Long single slit sinc^2");
    expect(maxwellPanel).toContain("Double slit / grating orders");
    expect(maxwellPanel).toContain("Ideal thin lens focal plane");
    expect(maxwellPanel).toContain("Coherence Demonstrator");
    expect(maxwellPanel).toContain("Coherence Demonstrator: double slit");
    expect(maxwellPanel).toContain("Degree of coherence |gamma12|");
    expect(maxwellPanel).toContain("Coherent fields");
    expect(maxwellPanel).toContain("Incoherent intensities");
    expect(maxwellPanel).toContain("Partial coherence");
    expect(maxwellPanel).toContain("Fringe visibility V");
    expect(maxwellPanel).toContain("V = (Imax - Imin) / (Imax + Imin)");
    expect(maxwellPanel).toContain("I = |U1|^2 + |U2|^2 + 2 Re(gamma12 U1 U2*)");
    expect(maxwellPanel).toContain("Gamma 1.00");
    expect(maxwellPanel).toContain("Gamma 0.50");
    expect(maxwellPanel).toContain("Gamma 0.00");
    expect(maxwellPanel).toContain("Coherent Map");
    expect(maxwellPanel).toContain("Incoherent Map");
    expect(maxwellPanel).toContain("Partial-Coherence Map");
    expect(maxwellPanel).toContain("Interference-Term Map");
    expect(maxwellPanel).toContain("Run Coherence Demo");
    expect(maxwellPanel).toContain("Coherence JSON");
    expect(maxwellPanel).toContain("Coherence Markdown");
    expect(maxwellPanel).toContain("Coherence CSV");
    expect(maxwellPanel).toContain("Coherence Demonstrator: double slit");
    expect(maxwellPanel).toContain("Advisor Review Mode");
    expect(maxwellPanel).toContain("Run Advisor Review");
    expect(maxwellPanel).toContain("Advisor Markdown");
    expect(maxwellPanel).toContain("Advisor JSON");
    expect(maxwellPanel).toContain("Advisor CSV");
    expect(maxwellPanel).toContain("y1 ~= 5.00 mm");
    expect(maxwellPanel).toContain("orders every 5.00 mm");
    expect(maxwellPanel).toContain("Slit JSON");
    expect(maxwellPanel).toContain("Slit Markdown");
    expect(maxwellPanel).toContain("Ideal thin lens focal-plane validation");
    expect(maxwellPanel).toContain("r1 ~= 1.22 lambda f / D = 61 um");
    expect(maxwellPanel).toContain("Lens phase");
    expect(maxwellPanel).toContain("Pupil D");
    expect(maxwellPanel).toContain("Numerical Focal Map");
    expect(maxwellPanel).toContain("Analytic Airy Map");
    expect(maxwellPanel).toContain("Focus Scan");
    expect(maxwellPanel).toContain("Run Lens Benchmark");
    expect(maxwellPanel).toContain("Lens JSON");
    expect(maxwellPanel).toContain("Lens Markdown");
    expect(maxwellPanel).toContain("Lens CSV");
    expect(maxwellPanel).toContain("runThinLensFocalValidation");
    expect(maxwellPanel).toContain("thinLensFocalValidationJson");
    expect(maxwellPanel).toContain("thinLensFocalValidationCsv");
    expect(maxwellPanel).toContain("runCoherenceDemonstrator");
    expect(maxwellPanel).toContain("coherenceDemonstratorJson");
    expect(maxwellPanel).toContain("coherenceDemonstratorCsv");
    expect(maxwellPanel).toContain("runSlitOrderValidation");
    expect(maxwellPanel).toContain("runAdvisorValidationReview");
    expect(maxwellPanel).toContain("slitOrderValidationJson");
    expect(maxwellPanel).toContain("advisorValidationReviewMarkdown");
    expect(maxwellPanel).toContain("Circular pinhole Airy/Bessel");
    expect(maxwellPanel).toContain("Circular aperture, not long slit");
    expect(maxwellPanel).toContain("hand-checkable scalar diffraction benchmarks with numerical results, analytic references, residuals, and report exports");
    expect(maxwellPanel).toContain("Computation mode");
    expect(maxwellPanel).toContain("Analytic Airy reference");
    expect(maxwellPanel).toContain("Numerical scalar propagation");
    expect(maxwellPanel).toContain("Compare numerical vs analytic");
    expect(maxwellPanel).toContain("Map grid");
    expect(maxwellPanel).toContain("Aperture radial");
    expect(maxwellPanel).toContain("Aperture angular");
    expect(maxwellPanel).toContain("Numerical Intensity Map");
    expect(maxwellPanel).toContain("Analytic Reference Map");
    expect(maxwellPanel).toContain("Residual Map");
    expect(maxwellPanel).toContain("Residual Curve");
    expect(maxwellPanel).toContain("Measured first min");
    expect(maxwellPanel).toContain("Finite-plane energy check");
    expect(maxwellPanel).toContain("Expected first Airy minimum");
    expect(maxwellPanel).toContain("Warning: first minimum is outside the 10 mm x 10 mm observation plane.");
    expect(maxwellPanel).toContain("Observation z");
    expect(maxwellPanel).toContain("Run Comparison");
    expect(maxwellPanel).toContain("Validation JSON");
    expect(maxwellPanel).toContain("Validation Markdown");
    expect(maxwellPanel).toContain("runCircularApertureValidation");
    expect(maxwellPanel).toContain("circularApertureValidationPipeline");
    expect(maxwellPanel).toContain("circularApertureValidationJson");
    expect(maxwellPanel).toContain("circularApertureValidationMarkdown");
    expect(maxwellPanel).toContain("Active solver backend");
    expect(maxwellPanel).toContain("PlanarTmmBackend");
    expect(maxwellPanel).toContain("ExternalFdtdBackend");
    expect(maxwellPanel).toContain("Future 3D Backends");
    expect(maxwellPanel).toContain("Scaffolded, not executable");
    expect(maxwellPanel).toContain("schema/export only in L6.0");
    expect(maxwellPanel).toContain("Export 3D FDTD Scaffold");
    expect(maxwellPanel).toContain("createMinimalMaxwellScene3D");
    expect(maxwellPanel).toContain("exportExternalFdtdScaffold");
    expect(maxwellPanel).toContain("externalFdtdSolverReceipt");
    expect(maxwellPanel).toContain("FEM/FDTD/BEM/RCWA");
    expect(maxwellPanel).toContain("solverBackend: run.solverBackend");
    expect(maxwellPanel).toContain("createMaterialCatalog");
    expect(maxwellPanel).toContain("listCatalogMaterials");
    expect(maxwellPanel).toContain("runCoatingSearch");
    expect(maxwellPanel).toContain("runRobustCoatingSearch");
    expect(maxwellPanel).toContain("runCoatingStack");
    expect(maxwellPanel).toContain("runCoatingSweep");
    expect(maxwellPanel).toContain("runCoatingDesignFoundry");
    expect(maxwellPanel).toContain("runCoatingYieldAnalysis");
    expect(maxwellPanel).toContain("serializeCoatingStackDesign");
    expect(maxwellPanel).toContain("parseMaterialImportJson");
    expect(maxwellPanel).toContain("Material Library");
    expect(maxwellPanel).toContain("MaterialPassport");
    expect(maxwellPanel).toContain("Template JSON");
    expect(maxwellPanel).toContain("Example Pack");
    expect(maxwellPanel).toContain("Example setup");
    expect(maxwellPanel).toContain("Incident medium, where light comes from");
    expect(maxwellPanel).toContain("Substrate medium, where light exits");
    expect(maxwellPanel).toContain("There is no 3D source-to-substrate distance in this solver.");
    expect(maxwellPanel).toContain("Planar Field Monitor");
    expect(maxwellPanel).toContain("Monitor CSV");
    expect(maxwellPanel).toContain("Design Foundry");
    expect(maxwellPanel).toContain("Apply Best");
    expect(maxwellPanel).toContain("Coating Stack Optimizer");
    expect(maxwellPanel).toContain("The optimizer tries selected materials, layer orders, and thicknesses.");
    expect(maxwellPanel).toContain("It does not search the internet or fetch new material data.");
    expect(maxwellPanel).toContain("Find Candidate Coatings");
    expect(maxwellPanel).toContain("Robust optimizer");
    expect(maxwellPanel).toContain("CoatingUncertaintyModel");
    expect(maxwellPanel).toContain("Shared deposition scale");
    expect(maxwellPanel).toContain("Shared offset + residual");
    expect(maxwellPanel).toContain("Independent P90");
    expect(maxwellPanel).toContain("formatUncertaintyReceipt");
    expect(maxwellPanel).toContain("Find Robust Coating Candidates");
    expect(maxwellPanel).toContain("Apply Robust Coating Candidate");
    expect(maxwellPanel).toContain("Robust Optimizer JSON");
    expect(maxwellPanel).toContain("Optimizer JSON");
    expect(maxwellPanel).toContain("Apply Coating Candidate");
    expect(maxwellPanel).not.toContain(">Coating Search<");
    expect(maxwellPanel).not.toContain(">Run Search<");
    expect(maxwellPanel).not.toContain(">Search JSON<");
    expect(maxwellPanel).not.toContain(">Apply Search<");
    expect(maxwellPanel).toContain("Tolerance Yield");
    expect(maxwellPanel).toContain("Yield JSON");
    expect(maxwellPanel).not.toMatch(/general 3D Maxwell solver ready|full 3D FEM Maxwell solver|arbitrary CAD Maxwell solved|production FEM\/BEM\/RCWA|3D Maxwell solve executed|full 3D Maxwell aperture solver|FDTD aperture solved|real thick lens solved|full stochastic 3D Maxwell simulated|real source statistics engine executed|certified calibration service|digital twin certified|manufacturing certified|EMVA compliant|pixel-level sensor stack executable|certified EMVA characterization executable|certified ISO 12233 result|Imatest-equivalent result|pure lens-only MTF certified|calibrated optical model fitting implemented|certified metrology report executable|lab accreditation workflow executable|hardware control implemented|AprilTag detector executable|ArUco detector executable/i);
  });

  it("keeps the visible app shell focused on L8.5 multi-element bench with L8.4/L8.3/L8.2/L8.1 FDTD and L7.8 diagnostics still reachable", () => {
    const app = readFileSync(resolve(testDir, "App.tsx"), "utf8");
    const simulationBuilder = readFileSync(resolve(testDir, "maxwell/SimulationBuilderPanel.tsx"), "utf8");
    const maxwellReturn = app.indexOf("return <MaxwellOnlyApp />;");
    const legacyWorkspace = app.indexOf('<main className="workspace">');

    expect(app).toContain('aria-label="Maxwell simulator"');
    expect(app).toContain("L8.5 Multi-Element Bench / L8.4 Aperture Validation / L7.8 Detector Round Trip");
    expect(app).toContain("Simulation Builder + Multi-Element FDTD Evidence");
    expect(app).toContain("L8.5 scalar chain preview and external FDTD chain fixtures");
    expect(app).toContain("L8.4 aperture validation");
    expect(app).toContain("L8.3 finite surface geometry export/import fixtures");
    expect(app).toContain("L8.2 benchmark sweeps");
    expect(app).toContain("Diagnostic Workbenches");
    expect(app).toContain("<SimulationBuilderPanel />");
    expect(app).toContain("<MaxwellPanel />");
    expect(simulationBuilder).toContain("L8.5 Multi-Element Optical Bench Propagation Chain");
    expect(simulationBuilder).toContain("Multi-Element Optical Bench");
    expect(simulationBuilder).toContain("Grid -&gt; source -&gt; element chain -&gt; target -&gt; observation / monitors -&gt; validation report.");
    expect(simulationBuilder).toContain("Load L8.5 Bench");
    expect(simulationBuilder).toContain("Add slit");
    expect(simulationBuilder).toContain("Add ideal lens");
    expect(simulationBuilder).toContain("Add transparent block");
    expect(simulationBuilder).toContain("Add absorbing block");
    expect(simulationBuilder).toContain("Add reflective plate");
    expect(simulationBuilder).toContain("Add blocker");
    expect(simulationBuilder).toContain("Add wedge");
    expect(simulationBuilder).toContain("Add monitor");
    expect(simulationBuilder).toContain("Run Scalar Preview");
    expect(simulationBuilder).toContain("Import Bundled Multi-Element Fixture");
    expect(simulationBuilder).toContain("Export Multi-Element Scene");
    expect(simulationBuilder).toContain("Export External FDTD Chain");
    expect(simulationBuilder).toContain("Export Multi-Element Validation Report");
    expect(simulationBuilder).toContain("Element Chain");
    expect(simulationBuilder).toContain("X-Z Bench Cross-Section");
    expect(simulationBuilder).toContain("Solver Plan");
    expect(simulationBuilder).toContain("Monitor Stack");
    expect(simulationBuilder).toContain("Scalar Chain Preview");
    expect(simulationBuilder).toContain("External FDTD Chain Import");
    expect(simulationBuilder).toContain("multielement_scene.json");
    expect(simulationBuilder).toContain("solver_plan.json");
    expect(simulationBuilder).toContain("monitor_stack.csv");
    expect(simulationBuilder).toContain("multielement_validation_report.md");
    expect(simulationBuilder).toContain("multielement_validation_report.json");
    expect(simulationBuilder).toContain("multielement_metrics.csv");
    expect(simulationBuilder).toContain("Simulation Builder");
    expect(simulationBuilder).toContain("1 Grid");
    expect(simulationBuilder).toContain("2 Source");
    expect(simulationBuilder).toContain("3 Elements");
    expect(simulationBuilder).toContain("4 Target / Material");
    expect(simulationBuilder).toContain("5 Compute");
    expect(simulationBuilder).toContain("6 Validate");
    expect(simulationBuilder).toContain("Surface Geometry Elements");
    expect(simulationBuilder).toContain("Add Transparent Block");
    expect(simulationBuilder).toContain("Add Absorbing Block");
    expect(simulationBuilder).toContain("Add Reflective Plate");
    expect(simulationBuilder).toContain("Add Aperture/Blocker");
    expect(simulationBuilder).toContain("Add Tilted Wedge");
    expect(simulationBuilder).toContain("L8.3 Surface Geometry Interaction Starter Set");
    expect(simulationBuilder).toContain("L8.3 surface geometry palette smoke preview");
    expect(simulationBuilder).toContain("L8.3 x-z cross-section geometry smoke preview");
    expect(simulationBuilder).toContain("L8.3 transparent block field smoke preview");
    expect(simulationBuilder).toContain("L8.3 absorbing block field smoke preview");
    expect(simulationBuilder).toContain("L8.3 reflective plate smoke preview");
    expect(simulationBuilder).toContain("L8.3 aperture blocker diagnostic smoke preview");
    expect(simulationBuilder).toContain("L8.3 wedge warning smoke preview");
    expect(simulationBuilder).toContain("Load Transparent Block Fixture");
    expect(simulationBuilder).toContain("Load Absorbing Block Fixture");
    expect(simulationBuilder).toContain("Load Reflective Plate Fixture");
    expect(simulationBuilder).toContain("Load Aperture Blocker Fixture");
    expect(simulationBuilder).toContain("Load Wedge Fixture");
    expect(simulationBuilder).toContain("Export Surface Geometry Scene");
    expect(simulationBuilder).toContain("Export Surface Geometry Report");
    expect(simulationBuilder).toContain("surface_geometry_scene.json");
    expect(simulationBuilder).toContain("surface_geometry_validation_report.md");
    expect(simulationBuilder).toContain("surface_geometry_validation_report.json");
    expect(simulationBuilder).toContain("surface_geometry_metrics.csv");
    expect(simulationBuilder).toContain("L8.4 Aperture / Blocker Edge-Diffraction Validation");
    expect(simulationBuilder).toContain("Aperture / Blocker Validation");
    expect(simulationBuilder).toContain("Add Long Slit");
    expect(simulationBuilder).toContain("Add Circular Pinhole");
    expect(simulationBuilder).toContain("Add Rectangular Aperture");
    expect(simulationBuilder).toContain("Add Opaque Blocker");
    expect(simulationBuilder).toContain("Load Long Slit Fixture");
    expect(simulationBuilder).toContain("Load Circular Pinhole Fixture");
    expect(simulationBuilder).toContain("Load Rectangular Aperture Fixture");
    expect(simulationBuilder).toContain("Load Opaque Blocker Fixture");
    expect(simulationBuilder).toContain("Import Aperture Run");
    expect(simulationBuilder).toContain("Export Aperture Scene");
    expect(simulationBuilder).toContain("Export Aperture Dossier");
    expect(simulationBuilder).toContain("aperture_validation_scene.json");
    expect(simulationBuilder).toContain("aperture_validation_report.md");
    expect(simulationBuilder).toContain("aperture_metrics.csv");
    expect(simulationBuilder).toContain("aperture_profile.csv");
    expect(simulationBuilder).toContain("single-slit-sinc2");
    expect(simulationBuilder).toContain("airy-bessel");
    expect(simulationBuilder).toContain("aperture cells across");
    expect(simulationBuilder).toContain("blocked power");
    expect(simulationBuilder).toContain("L8.2 External FDTD / Field Maps");
    expect(simulationBuilder).toContain("L8.1 FDTD export readiness smoke preview");
    expect(simulationBuilder).toContain("L8.1 Meep script export smoke preview");
    expect(simulationBuilder).toContain("L8.1 field slice import smoke preview");
    expect(simulationBuilder).toContain("L8.1 FDTD flux validation smoke preview");
    expect(simulationBuilder).toContain("L8.1 unsupported geometry warning smoke preview");
    expect(simulationBuilder).toContain("L8.2 FDTD Verification Suite");
    expect(simulationBuilder).toContain("L8.2 FDTD benchmark suite smoke preview");
    expect(simulationBuilder).toContain("L8.2 sweep plan smoke preview");
    expect(simulationBuilder).toContain("L8.2 convergence import smoke preview");
    expect(simulationBuilder).toContain("L8.2 Fresnel convergence smoke preview");
    expect(simulationBuilder).toContain("L8.2 absorber convergence smoke preview");
    expect(simulationBuilder).toContain("L8.2 PML warning smoke preview");
    expect(simulationBuilder).toContain("Generate Sweep Plan");
    expect(simulationBuilder).toContain("Export Benchmark Pack");
    expect(simulationBuilder).toContain("Load Transparent Convergence Fixture");
    expect(simulationBuilder).toContain("Load Absorber Convergence Fixture");
    expect(simulationBuilder).toContain("Import Convergence");
    expect(simulationBuilder).toContain("Export Benchmark Dossier");
    expect(simulationBuilder).toContain("fdtd_benchmark_manifest.json");
    expect(simulationBuilder).toContain("fdtd_sweep_plan.json");
    expect(simulationBuilder).toContain("fdtd_expected_reference.json");
    expect(simulationBuilder).toContain("fdtd_benchmark_report.md");
    expect(simulationBuilder).toContain("fdtd_convergence_metrics.csv");
    expect(simulationBuilder).toContain("fdtd_run_table.csv");
    expect(simulationBuilder).toContain("Export FDTD Manifest");
    expect(simulationBuilder).toContain("Export Meep Script");
    expect(simulationBuilder).toContain("Import Field Run");
    expect(simulationBuilder).toContain("Load Transparent FDTD Fixture");
    expect(simulationBuilder).toContain("Load Absorbing FDTD Fixture");
    expect(simulationBuilder).toContain("fdtd_scene_manifest.json");
    expect(simulationBuilder).toContain("meep_scene.py");
    expect(simulationBuilder).toContain("fdtd_validation_report.md");
    expect(simulationBuilder).toContain("External FDTD export/import only");
    expect(simulationBuilder).toContain("browser app does not execute FDTD");
    expect(simulationBuilder).toContain("Benchmark convergence evidence, not new in-browser physics.");
    expect(simulationBuilder).toContain("L8.0 optical-axis diagram smoke preview");
    expect(simulationBuilder).toContain("L8.0 surface validation smoke preview");
    expect(simulationBuilder).toContain("simulation_builder_scenario.json");
    expect(simulationBuilder).toContain("validation_report.md");
    expect(simulationBuilder).toContain("validation_report.json");
    expect(simulationBuilder).toContain("validation_metrics.csv");
    expect(simulationBuilder).toContain("Iteration count is not validation.");
    expect(simulationBuilder).toContain("arbitrary 3D Maxwell");
    expect(simulationBuilder).toContain("FDTD/FEM/BEM/RCWA execution");
    expect(simulationBuilder).toContain("manufacturing certification");
    expect(simulationBuilder).not.toMatch(/full 3D Maxwell execution is implemented|browser FDTD execution is available|FDTD execution is available in the browser|digital twin certified|manufacturing certification available/i);
    expect(maxwellReturn).toBeGreaterThan(0);
    expect(maxwellReturn).toBeLessThan(legacyWorkspace);
  });

  it("keeps L7.8.1 CI and bundle hygiene guardrails explicit", () => {
    const workflow = readFileSync(resolve(testDir, "../../../.github/workflows/deploy-pages.yml"), "utf8");
    const viteConfig = readFileSync(resolve(testDir, "../vite.config.ts"), "utf8");

    expect(workflow).toContain("actions/checkout@v6");
    expect(workflow).toContain("actions/setup-node@v6");
    expect(workflow).toContain("node-version: 24");
    expect(workflow).toContain("actions/upload-pages-artifact@v5");
    expect(workflow).toContain("actions/deploy-pages@v5");
    expect(workflow).not.toContain("actions/checkout@v4");
    expect(workflow).not.toContain("actions/setup-node@v4");
    expect(workflow).not.toContain("actions/deploy-pages@v4");
    expect(workflow).not.toContain("FORCE_JAVASCRIPT_ACTIONS_TO_NODE24");
    expect(viteConfig).toContain("manualChunks");
    expect(viteConfig).toContain("maxwell-panel");
    expect(viteConfig).toContain("core-measurement");
    expect(viteConfig).toContain("core-workspace");
    expect(viteConfig).toContain("core-maxwell");
    expect(viteConfig).not.toContain("core-shared");
    expect(viteConfig).not.toContain("chunkSizeWarningLimit");
  });
});
