# Optional external Meep scaffold for Transparent slab
# Generated by L8.8 deterministic campaign fixtures.
# Browser FDTD execution is not implemented; adapt this file in an external Meep environment if needed.
SCENARIO_ID = "transparent-slab"
SCENE_HASH = "b9e9d2c32c66a0a6"
REFERENCE_MODEL = "planar-tmm-stack"
