# Optional external Meep scaffold for Reflective plate
# Generated by L8.8 deterministic campaign fixtures.
# Browser FDTD execution is not implemented; adapt this file in an external Meep environment if needed.
SCENARIO_ID = "reflective-plate"
SCENE_HASH = "9bea0bd00510266d"
REFERENCE_MODEL = "ideal-mirror"
